### ISSUE TITLE
+Infinity / -Infinity for dates

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#1026]
@brianc 

Could you, please, re-run all your tests for this change: https://github.com/bendrucker/postgres-date/issues/3

It is quite an important one, and we want to be sure it didn't break anything.

Initial trace: https://github.com/vitaly-t/pg-promise/issues/142

**Comment by dytsai** [comment]
It did indeed break my code because I had an null equal check for infinity type. It used to return null but now "Infinity" instead. It took me a while to find this out because I got several environments with the same version node-postgres (4.5.1) but only some of them broke. It turned out it's postgres-date which broke my code. I guess it's better that node-postgres either uses exact version in package json dependency or postgres-date should bump its version higher like 2.0 since it's a breaking change.

**Comment by vitaly-t** [comment]
It is a minor breaking change, because it is unusual to send `Infinity` into a `date` field and then expect back a `null`. After all, it is against the PostgreSQL spec, which is what has been corrected by this change.

**Comment by bendrucker** [comment]
> I guess it's better that node-postgres either uses exact version in package json dependency or postgres-date should bump its version higher like 2.0 since it's a breaking change.

I disagree. This was a bug fix. All changes have the potential to break code, especially with workarounds built to fix the original bug (as in your case). 

`npm shrinkwrap` is great for avoiding the possibility of your build suddenly breaking because of downstream package changes. 

My workflow for avoiding situations like this is to add a unit test against a workaround like you've described. `npm shrinkwrap` prevents tests from suddenly failing and then when I do update I can immediately see if a hack that worked before is now broken.

**Comment by dytsai** [comment]
@bendrucker I agree. We do have tests. It's just that we didn't run them since there was no code or dependency change while deploying to some other boxes. We didn't expect the dependency change would break the code. Thanks for the suggestion of shrinkwrap.

**Comment by vitaly-t** [comment]
I believe this has been sorted by now.
