### ISSUE TITLE
Slow connection pool

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#1028]
One of the key ideas around using a connection pool is to make the connections much faster, because they are cached, as opposed to the physical connections.

I had a chance to benchmark how fast connections are within this library, and here're the results.

Using the direct connection I get an average of 25 milliseconds:
```js
var client = new pg.Client(cn);

var start = Date.now();
client.connect(function(){
     console.log("Delay:", Date.now() - start);
     client.end();
);
```

Using the connection pool, I'm getting an average of 28 milliseconds:
```js
var start = Date.now();
pg.connect(cn, function(done){
    console.log("Delay:", Date.now() - start);
    done();
});
```

Considering that the second approach implies reuse of the existing connection, it is awfully slow. In fact, it is so slow, that in a system with a small database your applications will spend way more time connecting and disconnecting than querying for data.

Pulling an existing connection from the connection pool should never take more than 1ms. In fact, it should always be way faster than 1ms.

Here's the complete test application for the connection pool:

```js
var nTrials = 1000, totalDelay = 0;

function doTest(idx) {
    var start = Date.now();
    pg.connect(cn, function (err, client, done) {
        if (err) {
            console.log("Error Connecting:", error);
            pg.end();
            process.exit();
        }
        totalDelay += Date.now() - start;
        done();
        if (idx === nTrials - 1) {
            console.log("Average Delay:", totalDelay / nTrials);
            pg.end();
        }
    });
}

for (var i = 0; i < nTrials; i++) {
    doTest(i);
}
```

Or is there something wrong with my test?

**UPDATE**

I've checked the `client.secretKey` on each request, and it is always the same, which means that I am getting the same connection from the pool for each request, so it should be very fast.

**Comment by langpavel** [comment]
Your test ask for connection all in parallel? Are you sure your benchmark makes sense?

**Comment by paulovieira** [comment]
@vitaly-t, that's interesting. But this happens because your benchmark is unrealistic: you are creating 1000 connections at the same time (in the same tick of the event loop). This doesn't make sense.

I reworked your  benchmark here: https://github.com/paulovieira/pg-lab/tree/master/connection_benchmark

In my benchmark the call to `.connect` is done 1 or 2 ms after the previous one, thus making sure they happen in different ticks (although the delay is random, so sometimes there is more than 1 connection in the same tick - that's ok, as long as there aren't many connections in the same tick).

The results show that obtaining the clients from the pool is indeed much faster than creating new clients on the fly:
```
MEAN VALUE - USING THE CLIENT POOL
global (all connections):  1.9

connections #0 to #10:  14.2
connections #10 to #20:  4.5
connections #20 to #30:  0.2
connections #30 to #40:  0
connections #40 to #50:  0
connections #50 to #60:  0
connections #60 to #70:  0
connections #70 to #80:  0
connections #80 to #90:  0
connections #90 to #100:  0.1
```
```
MEAN VALUE - USING NEW CLIENTS
global (all connections):  22.86

connections #0 to #10:  25
connections #10 to #20:  29.2
connections #20 to #30:  31.4
connections #30 to #40:  30.9
connections #40 to #50:  30.9
connections #50 to #60:  29.5
connections #60 to #70:  26.1
connections #70 to #80:  18.1
connections #80 to #90:  4.9
connections #90 to #100:  2.6
```

This example has the default `poolSize` value: 10. The mean value is calculated for the different segments of the array where the waiting time is stored. We can see clearly that the first 10 connections take some time, but after than they are instantaneous.

**Comment by brianc** [comment]
I'm +1 with what @paulovieira said.

**Comment by vitaly-t** [comment]
I've been meaning to close this, but forgot, sorry!

**Comment by brianc** [comment]
No problemo! 💃   Believe me - I understand the feeling of being overwhelmed w/ open issues. ;)
