### ISSUE TITLE
QueryQueue events overriden

### ISSUE THREAD

**Issue by imerani** [brianc/node-postgres#1073]
Hello:
     I'm trying to run multiple insert queries using a client (I'm ussing pool). I'm attaching an 'end' event to each query, which has to add the PK of the inserted row to a result array, in order to return the successful ones. I'm creating the queries and events inside a loop. Seems like the end event is being overridden, because finally, if I insert 10 records, I get an array with 10 equal items, like 1 event was executed 10 times instead of 10 events executed once. This is my code

```
pool.connect(function(err, client, release) {
    if (insert != null && insert.length > 0) {
        for (var i = 0; i < insert.length; i++) {
            var values = insert[i];
            var q = squel.insert().into(table).setFields(insert[i])
                    .toString();
            var ret = getPrimaryKeys(data.pk, values);
            var query = client.query(q);
            query.on('end', function(result) {
                updated.push(ret);
                console.log(ret);
            });
            query.on('error', console.log);
        }
    }
```

......

this is what I get

{ id: 'a6c2d6df-93cd-4129-a5bf-618e25971e7a' }
{ id: 'a6c2d6df-93cd-4129-a5bf-618e25971e7a' }
{ id: 'a6c2d6df-93cd-4129-a5bf-618e25971e7a' }
{ id: 'a6c2d6df-93cd-4129-a5bf-618e25971e7a' }
{ id: 'a6c2d6df-93cd-4129-a5bf-618e25971e7a' }
{ id: 'a6c2d6df-93cd-4129-a5bf-618e25971e7a' }
{ id: 'a6c2d6df-93cd-4129-a5bf-618e25971e7a' }
{ id: 'a6c2d6df-93cd-4129-a5bf-618e25971e7a' }
{ id: 'a6c2d6df-93cd-4129-a5bf-618e25971e7a' }
{ id: 'a6c2d6df-93cd-4129-a5bf-618e25971e7a' }

Am I doing something wrong?

thanks

**Comment by dedupely** [comment]
I'm having the same issue. Sending pgnotify events from my Dlang application, where a nodejs script is listening for events to handle a job queue. Having two (or more) events notify immediately after one another, I've noticed (more than once) tends to make the first event override the ones after it.

This really sucks because I keep seeing things "hanging" when in reality it was most likely two many events being triggered too close together from multiple threads or processes.

Redis is actually my alternative, I'm testing to see if this happens in redis as well.
