### ISSUE TITLE
Is there something similar to query.on('end' in Pool?

### ISSUE THREAD

**Issue by arjungowdaa** [brianc/node-postgres#1088]
Hi,

I was implementing the Connection Pool and followed the instructions given in https://github.com/brianc/node-postgres
Below is my code
```
var express       = require('express');
var pg            = require('pg');

var CONSTANT      = require('../src/constant.js');
var QUERY         = require('../src/queries.js');

var router = express.Router();

var config = {
  user: CONSTANT.DB_USERNAME,
  database: CONSTANT.DB_SCHEMA,
  host: CONSTANT.DB_HOST,
  port: CONSTANT.DB_PORT
};
console.log("config : "+JSON.stringify(config));
var pool = new pg.Pool(config);

router.get('/getAllRegionTypes', function(req, res, next) {
  var results = [];
  pool.query(QUERY.GET_ALL_REGION_TYPES, function(err, res) {
    if (err) throw err
    console.log("res.rows : "+JSON.stringify(res.rows));
    results.push(res.rows);

    //return res.json(results);
  })

  pool.on('error', function(error, client) {
    console.error('idle client error', err.message, err.stack);
    return res.status(500).json({ success: false, data: err});
  })
})

module.exports = router;
```

If you see am not having the password in config object. Below are my questions/clarifications
1) I have set the `PGPASSFILE` env variable which is referring to a `pgpass.conf` file.
pgpass.conf file has `*:*:*:*:PASSWORD`.
So when I say `new pg.Pool(config)` am assuming internally password is being read from pgpass.conf file. Am I correct?
2) I wanted to return the json response back to client but when I say `return res.json(results);` I get the error message `TypeError: res.json is not a function`. Why is that?
3) Just like there is `query.on('end'` is there something similar to that in Pool?
4) While am using the connection pooling, should I have the code to return the client back to pool and things like that?

These are the questions as of now.

**Comment by brianc** [comment]
1) no, the pool will not read from your passfile. You need to do this ahead of time and pass the read results into the pool constructor. You can use [this module](https://github.com/hoegaarden/pgpass) to read the pass file

2) this is not related to node-postgres, it's related to the express api. with that being said try `res.send(results)` instead of `res.json` - newer versions of express might have removed `res.json`

3) no - if you need an end event or the full query object you'll need to check out a client & run the query...

```js
pool.client((err, client, release) => {
  const query = client.query('select now()')
  query.on('end', () => release())
})
```
or something like that - generally using the `end` event isn't necessary but if you want it for some reason its available that way.

4) yes absolutely. if you check out a client from the pool and don't return it your application *will* exhaust the pool and become unresponsive.  Using `pool.query` does this for you so you don't have to worry about it.
