### ISSUE TITLE
New Pool overview

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#1093]
@brianc 

Understandingly, the addition of the new `Pool` object was to add more flexibility to the library, particularly when it comes to using more than one pool in a single application.

However, the way this feature was introduced into the library tends to create more problems than it solves, and mostly for those who use the library for the first time.

It should have been added as an extra/advanced feature, one than can be optionally used instead of using the default pool, not as a replacement.

Because it was introduced as a replacement, the newcomers are now bombarding all forums with the same questions - confusion around the new connection pool, which in fact they do not need to begin with.

The thing is, the new feature only benefits a tiny percentage of projects where more than one connection is needed. The rest of the time, and especially for new projects, the default pool is all that's needed, and anything else just gets in the way. Evidence to that is all over the place by now.

I think it is worth retracting some steps back, making it so that the default pool is right in your face when you are first introduced to the library, moving the separate pool usage into an advanced section, and with some implementation changes to cater for that.

**Comment by brianc** [comment]
> It should have been added as an extra/advanced feature, one than can be optionally used instead of using the default pool, not as a replacement.

the "default" pool is going to be deprecated before `pg@7.0` and removed entirely. I'm convinced a singleton as an interface to a module is just bad API design decision I made years ago. I've not been using a singleton pool in my own apps for a long time.

> the newcomers are now bombarding all forums with the same questions - confusion around the new connection pool, which in fact they do not need to begin with.

newcommers, oldcommers, all users need a connection pool when interacting with postgres in a highly concurrent or high load environment.  

If there are questions on usage I'm not seeing them in the GH issues for this repo.  if the documentation and examples I've written aren't good enough I'm totally open to writing more or accepting more documentation through pull requests!  All it takes is editing the markdown on github and sending in a PR.  💃 

> The thing is, the new feature only benefits a tiny percentage of projects where more than one connection is needed. The rest of the time, and especially for new projects, the default pool is all that's needed, and anything else just gets in the way. Evidence to that is all over the place by now.

I have seen no evidence. 

Yes, it's a few extra lines of "boilerplate" code to set up a pool now. This is your database pool for your entire application - it should be explicitly set up and regarded as important. Regardless, if someone wants to use a different pool implementation they can implement their own as a standalone module (as I have now done with pg-pool).  `pg.Client` will never go away, and that's a totally unpooled connection completely controlled by the user.  

More options makes the ecosystem better: having a global singleton with hard to use require/release semantics has resulted in endless support headaches for me, my own apps, and the hundreds of bug reports & discussions I've fielded on the issue.

> I think it is worth retracting some steps back, making it so that the default pool is right in your face when you are first introduced to the library,

Making the default pool usage right in your face when you get to the documentation is a great idea: that's what I was trying to do w/ the documentation changes I did here to the readme.  I'm totally open to iterating on the docs more and making it more explicit and easier to follow! I'm happy to discuss and work on documentation changes!  Let's spend our energy on better docs rather than reverting back to a bad API from years gone by. 😄
