### ISSUE TITLE
pg.defaults.poolSize vs pg-pool

### ISSUE THREAD

**Issue by lucky-libora** [brianc/node-postgres#1102]
Hey all!

Can somebody describe difference between pg.defaults.poolSize and max value for pg-pool ?

Yesterday I upgraded my app with new version of pg and started using pg-pool as described in wiki.
Today I noticed  that average count of active backend postgres proccesses had decreased significantly but average response time increased by 5ms.

I know it is not is big number but I just want to understand what was changed inside?

**Comment by brianc** [comment]
`pg.defaults.poolSize` and the max value for `pg-pool` are the same value, used internally by the pool the same way.  Using `pg-pool` directly just doesn't read from the `pg.defaults` stuff because, really, it's kinda gross having globally accessable & mutable config values like that...better to pass them directly into the pool.  But...they affect the pool in the same way.

**Comment by lucky-libora** [comment]
Thanks a lot!

One more question if you don't mind.

How `idleTimeoutMillis` config value affects performance of application?

**Comment by brianc** [comment]
@lucky-libora you wont notice a perf difference with `idleTimeoutMillis` and _definitely_ wont notice under heavy load.  I usually just leave it at 30 seconds but its handy to turn down to 500 millis or something if you're writing a script that you want to exit soon after it goes idle instead of hanging out for 30 seconds before idling.

**Comment by lucky-libora** [comment]
Thnx a lot

**Comment by brianc** [comment]
My pleasure! :dancer:
