### ISSUE TITLE
pg.connect is undocumented

### ISSUE THREAD

**Issue by seishun** [brianc/node-postgres#1238]
The `pg.connect` function is not mentioned in the [README](https://github.com/brianc/node-postgres/blob/master/README.md) or the [wiki](https://github.com/brianc/node-postgres/wiki/pg). But the function exists and it's present in a lot of example code on the Internet.

Is it deprecated? Is using `new pg.Pool()` preferred to `pg.connect`? Or are they both fully supported? Either way, it would be nice to have this function mentioned somewhere, so that people know which way to write their own code.

**Comment by charmander** [comment]
Yes, `pg.Pool` instances are preferred to `pg.connect`.

**Comment by brianc** [comment]
Yeah `pg.connect` is soft deprecated.  I'm probably not going to remove it for a long time, but I'd recommend using an instance of a pool instead of `pg.connect` - global singletons like `pg.connect` are _generally_ a nasty design pattern.  My self from 6 years ago didn't think that one all the way through. :p

**Comment by seishun** [comment]
Thank you for the clarification.

>SO the thinking goes don't document it anymore

I think it would be better to document it. A simple mention like "`pg.connect` is an old thing, don't use it" would be enough to avoid confusion by newcomers.

**Comment by charmander** [comment]
> SO the thinking goes don't document it anymore, mark it deprecated in a future version, and eventually remove it and roll out a monkey-patch into a separate node-module so if you absolutely need backwards compatibility you can install it still.

Can that future version be the next version? =)

**Comment by pstef** [comment]
I prefer to have a single connection from the application's perspective. This is because I already use a connection pooler that is external from this perspective. It seems to me that using pg's built-in connection pooler would buy me nothing at the expense of introducing concepts that my application doesn't need.

**Comment by charmander** [comment]
@pstef You would want `pg.Client`, then. `pg.connect` uses a singleton pool.

**Comment by brianc** [comment]
I added this to the docs milestone so I'll include it as deprecated when I write them up.

**Comment by Yitzi2** [comment]
Question: What would then be the proper equivalent to the code shown at https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js?

**Comment by charmander** [comment]
`pg.connect` has been removed; is this okay to close?

**Comment by brianc** [comment]
👍 definitely good to close
