### ISSUE TITLE
pg-native slows down throughput

### ISSUE THREAD

**Issue by aphusion** [brianc/node-postgres#1273]
I have a query that retrieves a lot of information from the DB so I thought using the pg-native would improve the performance.

I installed the requirements and added the ".native" and made sure the pool was also created from the native module, however, performance drops by over 20% when I do that.  Is there anything I should be looking for?

**Comment by brianc** [comment]
Weird! I've seen pg-native usually around 20% faster, depending on the benchmark.  Here are a few tips:

- Don't parse the data types of the query. Postgres protocol returns everything as strings - some parsing can take lot of time depending on the type.

Set `arrayMode = true` on the client.  This prevents the query from building up objects and instead returns them as arrays - depending on your throughput and particular use case this can also help.

Use pg-native library directly as well.

```js
const Client = require('pg-native')
const client = new Client({
  arrayMode: true,
  // return the identity function as the type parser for every data type
  types: { getTypeParser: () => (val) => val }
})
```

It's really hard to tell where the perf is impacted exactly without diving into your particular code base.  If you need more customized help I'm happy to consult with you or your company. Please contact me [by email](brian.m.carlson@gmail.com) if you're interested in pursuing that.

Otherwise, I hope this helps!
