### ISSUE TITLE
automatically convert js object into SQL when INPUT/REPLACE

### ISSUE THREAD

**Issue by red010182** [brianc/node-postgres#1277]
This is a feature request.

Hi, everyone, I'm coming from MySQL and really love one feature of node-mysql lib, which I hope node-postgres could have as well:

```
user table
=============
id (INT)
name (VARCHAR)
age (INT)
```

```
let dict = { 
    name: "username", 
    age: 18
};

pool.query('INSERT INTO user SET $1', [dict], (err,result){
//...
});

```
It's really helpful if it could automatically transferred into the following SQL
```
INSERT INTO user (name,age) VALUES ("username",18);
```

Or even further, support multiple row insert:
```
let users = [
    {
        name: "Bill",
        age: 18
    },
    {
        name: "Andy",
        age: 28
    }
]

pool.query('INSERT INTO user SET (?);', [users], (err, result) => {});
```
could converts into:
```
'INSERT INTO user (name,age) VALUES ("Bill",18), ("Andy",28);

```

**Comment by sehrope** [comment]
This type of thing is better served in a helper layer atop the driver. The driver is focused on executing SQL commands as provided, not transforming them.

Regarding the idea itself, I don't think it's possible to do what you describe in a generic / robust way that is inferred automatically from the SQL. Unless you have a full fledged SQL parser, the best you could do is match for some common patterns (ex:`"INSERT INTO <table> SET ?"`) but it'd be very brittle.

If you're going to implement something like this yourself (say for your own app or a separate library), I'd suggest making it an explicit command (ex: `MyHelper.superInsert(tableName, params)`) and generating the resulting SQL command from tableName + params rather than trying to infer it from a special SQL string pattern. Also, if you're going to be generating SQL make sure to escape any identifiers prior to concatenating them into a SQL string.

**Comment by brianc** [comment]
@red010182 thanks for the feature request!  Everything @sehrope said is right on.  I'd encourage you to write a module if you find a generic solution and when you do, come back and add it to the [wiki](https://github.com/brianc/node-postgres/wiki/Extras)!
