### ISSUE TITLE
Prepared Statement In ORDER BY Clause Doesn't Work

### ISSUE THREAD

**Issue by Kuchiriel** [brianc/node-postgres#1284]
Hello fellow coders (:

This is my query
```
 request.pg.client.query({
    text: `select  
    email,
    name,
    role,   
    place  
    from users
    order by $1 desc`,
    values: [request.query.sort]
  }, (err, result) => {
```
`request.query.sort` defaults to 'name', but doesn't work.

![image](https://cloud.githubusercontent.com/assets/4648891/25882679/ae9f2846-351b-11e7-9943-b52feaedb360.png)

Is this an issue or am I doing something wrong?

Thanks in advance!

**Comment by sehrope** [comment]
What you're trying won't work because the $1 is a parameter, not an identifier, so you can't refer to a column with it. Your code ends up sorting by a fixed value (the value of the $1 parameter) which would not impact the sort at all as it's the same for every row.

You'll need to generate the query in JS by concatenating the string prior to executing it. Make sure to whitelist the possible choices of the order by column otherwise someone could put something like `1 UNION ALL SELECT ...` as the `sort` field of the request (i.e. SQL injection).

**Comment by Kuchiriel** [comment]
@sehrope, followed your advice, now everything works fine. Thank you very much!

**Comment by HoppeDevz** [comment]
@sehrope, thx!
