### ISSUE TITLE
Docs: document async/await example w/ express

### ISSUE THREAD

**Issue by brianc** [brianc/node-postgres#1306]

**Comment by tonylukasavage** [comment]
Can you give a little context as to what this is regarding? I'm currently having an issue with pg (as used in pg-promise) where the stack traces I'm getting from failed db queries leveraging async/await in a mocha test suite are pretty useless. For example, I'm getting back something like this:

```
error: syntax error at or near "$"
      at Connection.parseE (node_modules/pg-promise/node_modules/pg/lib/connection.js:539:11)
      at Connection.parseMessage (node_modules/pg-promise/node_modules/pg/lib/connection.js:366:17)
      at Socket.<anonymous> (node_modules/pg-promise/node_modules/pg/lib/connection.js:105:22)
      at readableAddChunk (_stream_readable.js:178:18)
      at Socket.Readable.push (_stream_readable.js:136:10)
      at TCP.onread (net.js:561:20)
```

No indication as to where the test failed or anything, just a trace referencing the underlying pg module. 

If this is in anyway related to what you're documenting, I'd love to know. If not, I can log another issue and get out of your hair.

**Comment by vitaly-t** [comment]
@tonylukasavage it is useful at least to leave a link after the issue has been sorted :wink:

https://github.com/vitaly-t/pg-promise/issues/342

**Comment by tonylukasavage** [comment]
@brianc you can ignore my comment above as after more digging my problem seemed to be specific to using Promises (via @vitaly-t's pg-promise), and thus are not the concerns of node-postgres. Sorry for the noise.

**Comment by geoffreyyip** [comment]
I have some recommendations for the current version of the node-postgres guide's [Document async/await example w/ Express](https://node-postgres.com/guides/async-express). Additions are in bold.

Express with async/await

My preferred way to use node-postgres (and all async code in node.js) is with async/await. I find it makes reasoning about control-flow easier and allows me to write more concice and maintainable code.

This is how I typically structure express web-applications with node-postgres to use async/await:

- app.js
- index.js
- routes/
  - index.js
  - photos.js
  - user.js
- db/
  - index.js <--- this is where I put data access code

That's the same structure I used in the project structure example.

My db/index.js file usually starts out like this:

```
const { Pool } = require('pg')

module.exports = {
  query: (text, params) => pool.query(text, params)
}
```

Then I will install express-promise-router and use it to define my routes. 
Here is my routes/user.js file:

```
const Router = require('express-promise-router')

const db = require('../db')

// create a new express-promise-router
// this has the same API as the normal express router except
// it allows you to use async functions as route handlers
const router = new Router()

// export our router to be mounted by the parent application
module.exports = router

router.get('/:id', async (req, res) => {
  const { id } = req.params
  const { rows } = await db.query('SELECT * FROM users WHERE id = $1', [id])
  res.send(rows[0])
})
```

**express-promise-router is a useful convenience, but it is not necessary for `async/await` syntax. express-promise-router acts as a drop-in-replacement for Express 4's Router to automatically handle Promise rejections. This is useful because `async/await` syntax uses Promises under the hood, and Promises swallows errors when no rejection handler is defined. To use `async/await` without `express-promise.router`, I could write the following:**

```
const router = require('express').Router();

const db = require('../db')

// export our router to be mounted by the parent application
module.exports = router

router.get('/:id', async (req, res, next) => {  // need to add the `next` parameter
  const { id } = req.params
  const { rows } = await db.query('SELECT * FROM users WHERE id = $1', [id])
    .catch((err) => next(err));  // this ensures express handles the error
  res.send(rows[0])
})
```

**Alternatively, I could do this:**

```
const router = require('express').Router();

const db = require('../db')

// export our router to be mounted by the parent application
module.exports = router

router.get('/:id', async (req, res, next) => {
  try {
    const { id } = req.params
    const { rows } = await db.query('SELECT * FROM users WHERE id = $1', [id])
    res.send(rows[0])
  } catch(err) {
    next(err);
  }
})
```

**This is a lot of boilerplate though. express-promise-router calls `next(err)` for us. Check out [the docs](https://github.com/express-promise-router/express-promise-router) for more info.**

Then in my routes/index.js file I'll have something like this which mounts each individual router into the main application:

```
// ./routes/index.js
const users = require('./user')
const photos = require('./photos')

module.exports = (app) => {
  app.use('/users', users)
  app.use('/photos', photos)
  // etc..
}
```

And finally in my app.js file where I bootstrap express I will have my routes/index.js file mount all my routes. The routes know they're using async functions but because of express-promise-router the main express app doesn't know and doesn't care!

```
// ./app.js
const express = require('express')
const mountRoutes = require('./routes')

const app = express()
mountRoutes(app)
```

// ... more express setup stuff can follow
Now you've got async/await, node-postgres, and express all working together!

**Comment by charmander** [comment]
Is this covered by https://node-postgres.com/guides/async-express/?

**Comment by brianc** [comment]
yah it is! good point!
