### ISSUE TITLE
Upgrade generic-pool to v3

### ISSUE THREAD

**Issue by brianc** [brianc/node-postgres#1308]
This is a breaking change for v7.0.  The next version of the pool has a lot more options.  I need to make sure to expose these options in the pg-pool constructor properly.

**Comment by vitaly-t** [comment]
> This is a breaking change for v7.0

I don't see any branch for and/or roadmap for v7.0. Any insight would be much appreciated, as to what to expect and roughly when.

> The next version of the pool has a lot more options

What are those?

**Comment by gajus** [comment]
> The next version of the pool has a lot more options

https://github.com/coopernurse/node-pool/tree/v3.1.7

**Comment by gajus** [comment]
`acquireTimeoutMillis` is something that'd be definitely useful.

`brianc` on the note of `generic-pool`, I think it would appropriate for the `pg-pool` to declare its own defaults as opposed to replying on the `generic-pool` configuration.

Similarly, the `README.md` is a bit misleading – after scanning the docs, I thought that whats presented in the `create` example (the pool configuration) is what the default configuration is. Thats not the case.

**Comment by brianc** [comment]
@gajus - what do you mean by declaring it's own defaults?  Do you mean instead of just passing `undefined` for any config value that isn't passed to pg-pool, pass in a preset one - even if it just mirrors what generic-pool uses?  That way if generic-pool changes it's defaults in the future we wont break? Do you have a code sample...that might help me understand!

I can also document the defaults if that would help?

**Comment by gajus** [comment]
> pass in a preset one - even if it just mirrors what generic-pool uses? That way if generic-pool changes it's defaults in the future we wont break?

Precisely.

Since the configuration is flat, the simplest way to do that is using `Object.assign`, e.g.

```js
const createConfiguration = (userConfiguration) => {
  const defaultConfiguration = {
    acquireTimeoutMillis: Infinity,
    autostart: true,
    evictionRunIntervalMillis: 0,
    fifo: true,
    idleTimeoutMillis: 30000,
    max: 1,
    maxWaitingClients: Infinity,
    min: 0,
    numTestsPerRun: 3
    priorityRange: 1,
    Promise: global.Promise,
    softIdleTimeoutMillis: -1,
    testOnBorrow: false
  };

  return Object.assign({}, defaultConfiguration, userConfiguration);
};

```

As far as I can tell from their docs, these are the defaults for the generic-pool v3.

> I can also document the defaults if that would help?

It is a bit odd when they are not in the docs. However, if you are mirroring `generic-pool` configuration, then simply linking to their documentation would be enough.

The reason this caught my attention in the first place is because I was debugging an instance where I was expecting an idle connection to time out after 1 second (false assumption made after looking into https://github.com/brianc/node-pg-pool). I had to go into the code to scout that you are using `generic-pool` and then look into their configuration defaults for the respective version.

**Comment by brianc** [comment]
Handling this here: https://github.com/brianc/node-pg-pool/pull/67
