### ISSUE TITLE
Row events with explicit "get next row"

### ISSUE THREAD

**Issue by rightfold** [brianc/node-postgres#1325]
Row events (`query.on('row', …)`) come in as fast as possible. Is there a way to do async processing in the row event handler, and not have the next row come in before this async event handler is done, other than queueing all the rows?

Alternatively, is there a `query.getNextRow(callback)` API that I can repeatedly call?

**Comment by brianc** [comment]
I'm encouraging people to stop using `query.on('row')` and instead use a callback or a promise for the general case.  I'm going to deprecate its general usage and put it behind a slightly different API in `pg@7.0` too because it feels like a stream _sorta_ but isn't and doesn't have the flow control or back-pressure guarantees of a stream.  I think it's hard for newcommers to the lib, it's a bit misleading, and generally not what you want to use.

Check these out instead - they should do exactly what you want:

https://github.com/brianc/node-pg-cursor
https://github.com/brianc/node-pg-query-stream

**Comment by rightfold** [comment]
Thanks! Cursor seems like what I need!

**Comment by brianc** [comment]
Yay! 💃  glad I could help
