### ISSUE TITLE
Add Support for DEFAULT in INSERT queries

### ISSUE THREAD

**Issue by DrLongGhost** [brianc/node-postgres#1339]
Consider the following:

```
return pg.queryOne({
    name: 'createItem',
    text: `INSERT INTO items (name, item_level, item_safety)
            VALUES ($1, $2, $3)`,
    values: [ name, itemLevel, itemSafety ]
  }
```

If you have two DEFAULT's configured in your database for item_level and item_safety and you want to make them optional fields in your API that inherit the default, you have several options:

1) Duplicate the default values in your application code
2) Duplicate the defaults in a BEFORE INSERT trigger that looks for null's in the INSERT
3) Write an abstraction layer that dynamically creates the INSERT query to contain only the non-null fields and assigns a different "name" for each permutation to avoid issues with caching

It would be nice if there were native support for using the DEFAULT keyword in the generated query via something like:

```
return pg.queryOne({
    name: 'createItem',
    text: `INSERT INTO items (name, item_level, item_safety)
            VALUES ($1, $2, $3)`,
    values: [ name, itemLevel || pg.DEFAULT, itemSafety || pg.DEFAULT ]
  }
```

Or maybe I'm missing something obvious and this is already supported somehow?

**Comment by brianc** [comment]
I don't think postgres supports passing the keyword `DEFAULT` to a prepared statement as a parameter so it's not possible to do w/ this driver.  If you find out otherwise please lemme know but judging by what the protocol supports I can't figure out how.  There might be a way to do it w/ if statements or CTEs in your query.  Otherwise you'd have to write an abstraction out for it I believe - or don't use a prepared statment, then it's not cached & you can send different forms easily.

**Comment by DrLongGhost** [comment]
That makes sense. Thanks for looking into it.

**Comment by lartey31** [comment]
Hi,
I had a question regarding your statement on Jul12, "Otherwise you'd have to write an abstraction out for it I believe - or don't use a prepared statement, then it's not cached & you can send different forms easily."

When say "don't use a prepared statement", what exactly do you mean. How else could we insert values from a form without a prepared statement. I am new to using POSTGRESQL and Node. I have a form with over 100 entry fields and I am trying to find out the best way to handle inserting date fields that are not required. Or even, inserting a row with over 100 columns of data.

**Comment by charmander** [comment]
@lartey31 You’d construct the statement based on your column list:

```js
let columns = [];
let values = [];

if (form.name) {
    columns.push('name');
    values.push(form.name);
}

// etc.

await pool.query(
    'INSERT INTO items (' + columns.join(', ') + ') ' +
        'VALUES (' + columns.map((_, i) => '$' + (i + 1)) + ')',
    values,
);
```

This is easier with a query builder.

**Comment by lartey31** [comment]
@charmander thanks for the quick response. I will message you privately to get some clarification, if you don’t mind.

**Comment by lartey31** [comment]
Hi @charmander ,

I am very late in getting back to you. What query builder do you recommend that I utilize?

Essentially I need a recommendation for the best approach to post a form with 100 data fields in a table within a postgresql database.

The issue that I am running into is with the date fields. If I leave the date fields empty I receive an error from the database stating that I cannot input "" into columns with the datatype "timestamp". Essentially I can not leave the date fields blank. That is where the exceptions come in. I need to handle blank date form fields.

In your earlier code you mentioned "form.name" Are you referring to the name attribute of the input field within the form that I get from body parser i.e., req.body.firstname or the actual name of the form from the html name attribute of the form.

Thanks in advance.
