### ISSUE TITLE
Uncommited transaction

### ISSUE THREAD

**Issue by fuqcool** [brianc/node-postgres#1340]

**Comment by brianc** [comment]
Lemme known if you have more details!

**Comment by fuqcool** [comment]
@brianc so sorry I mis pressed *enter* , and it just created the issue with no content.

**Comment by sibedge** [comment]
@fuqcool When you call `done()`, you are releasing the connection back to the pool, so it becomes available on the next request. And since you didn't close the transaction with `COMMIT / ROLLBACK`, it remains open until either `COMMIT / ROLLBACK` is executed, or the corresponding connection is closed.

As a result, in some other place in your code when you request a connection, you get the same connection that was used for the unfinished transaction, which in turn leaks the data of the transaction state, naturally.
