### ISSUE TITLE
parameterized query with an IN operator

### ISSUE THREAD

**Issue by thewizarodofoz** [brianc/node-postgres#1452]
Is it possible to use a parameterized query with an `IN` operator?

I'm imagining something like:
```js
const text = 'SELECT * FROM tbl WHERE col1 IN ($1) AND col2 = $2';
const values = [[1, 2, 3], 1000000];
```

Currently I'm injecting the values for `IN` using a string template:
```js
const text = `SELECT * FROM tbl WHERE col1 IN (${[1, 2, 3].join(', ')}) AND col2 = $1`;
const values = [1000000];
```

**Comment by charmander** [comment]
Use an array parameter. (https://github.com/brianc/node-postgres/issues/82#issuecomment-18756081, https://github.com/brianc/node-postgres/issues/129#issuecomment-48633017, #623)

```js
const text = 'SELECT * FROM tbl WHERE col1 = ANY ($1) AND col2 = $2';
const values = [[1, 2, 3], 1000000];
```

**Comment by matt212** [comment]
@charmander 
well below is not working 
```
const text = 'SELECT * FROM employees WHERE lower(a."first_name") IN ($1)   AND lower(a."gender") IN ($2)';
const values = [['aamer','babette'], ['f']];
```
what would be correct way to use above

**Comment by brianc** [comment]
where = any($1)

**Comment by matt212** [comment]
thanks @brianc 
so my final where clause looks like this 

`and  lower(a."gender") = ANY ($1) and lower(a."first_name") = ANY($2) ` 
cool

**Comment by brianc** [comment]
perfecto!

**Comment by brianc** [comment]
yup!

**Comment by mingfang** [comment]
So ANY works but IN does not work.
is this a bug or a feature?

**Comment by rockie** [comment]
How about NOT IN?

**Comment by sehrope** [comment]
For the reverse you can use `ALL(...)` in the same manner:

```
SELECT *
FROM some_table t
WHERE t.id != ALL($1::int[])
```

(*Though watch out with indexing on that kind of thing as it'll probably be a full scan.*)


Good to keep in mind that:

* With `=` you almost always want to use `= ANY(...)`
* With `!=` you almost always want to use `!= ALL(...)`

Otherwise if there's more than one value in the list of values, the negated operators don't really make sense. For example, `x != ANY('{1,2,3}'::int[])` will always be true because if the value matches any one item of the array, it definitely does not match the rest. Similarly, `x = ALL('{1,2,3}'::int[])` will always be false because a value cannot equal more than one thing.

**Comment by evgeny-kim** [comment]
Using pg-format:

```javascript
import pgFormat from 'pg-format';

const query = pgFormat(`select ... where field in %L`, values[]);
const result = await pool.query(query);
```
