### ISSUE TITLE
Transaction start while in start state errors..

### ISSUE THREAD

**Issue by arsinawaz** [brianc/node-postgres#1461]
Hi, 

I have a question, how does node-postgres execute queries? Does it call commit after query has been executed or what is the process of querying from the DB?

I am getting "transaction start while in start state" after a days of investigation i found out that the multiple queries sometimes are running in one transaction which might lead to "transaction start while in start state" error cases.

P.S. i am only calling functions in the DB from node so no plain queries just some SELECT functionName(Parameters or no parameters); ..

My config:
"pg": "^6.1.2",
Node: v6.10.0

Any kind of help is appreciated.

Thanks

**Comment by sehrope** [comment]
The node-postgres driver has no built-in handling for transactions. It's done by the user by manually executing BEGIN / ROLLBACK / COMMIT commands with a Client (i.e. with a connection). It's the caller's responsibility to ensure the client resources are correctly managed and released back to the pool when the transaction is completed.

If you're encountering an error make sure to post the entire error message and if possible stack trace of your program and/or a reproducible snippet of the program itself.

**Comment by arsinawaz** [comment]
This is the error message from Node-postgres:
![image](https://user-images.githubusercontent.com/6444617/30863832-7d10d6f6-a2eb-11e7-8533-d0b18261f103.png)


and here is error stack from postgres DB:
![image](https://user-images.githubusercontent.com/6444617/30863794-5c71b488-a2eb-11e7-9abc-c46d93cef30b.png)

**Comment by sehrope** [comment]
The server log shows a segmentation fault on the backend. That's a server issue and has nothing to do with the driver. I'd suggest trying to reproduce that using pure SQL (say from psql) and, if you can, report it either the pgsql-general or pgsql-hackers mailing lists.

Separately you should be using an explicit pool (rather than `pg.connect(...)`) and need to call `done(err)` to have the pool throw out the bad connection if it's errant. Otherwise it could be re-used. I suggest going through the docs/examples on the wiki for guidelines of how to use this library.

**Comment by arsinawaz** [comment]
I am calling done() at the end of callback function, wouldn’t that be sufficient or do i need to call it in error case separaly and provide err object as parameter?

**Comment by brianc** [comment]
Yah this looks like a segfault unrelated to node-postgres.  Please feel free to open another issue if something is reproducible from this lib.
