### ISSUE TITLE
Inserting current Date in postgres with or without timezone column

### ISSUE THREAD

**Issue by RaviDavda** [brianc/node-postgres#1583]
When I am trying to insert current date in a timestamp without timezone or in a timestamp with timezone, It gives me error like **time zone "gmt+0530" not recognized**. Below is my query.

var currentDate = new Date() 
console.log(currentDate)

client.query('INSERT into freedom_account_plan_master (account_plan_id, planname, visibility_details, amount, validity_days, allowed_moderator, allowed_custom_emoticons, paid_moderators_fee, paid_custom_emoticons_fee, system_emoticons_discount, set_password_fee, username_change_fee, entry_fee, collection_percentage, plantype_id, plan_priority, created_at, is_active) VALUES (1, \'Free Account\', \'Lowest Visibility\', 0, 0, 2, 0, 200, 250, 0, 80, 500, 200, 20, 1, 1, ' + currentDate + ', true), (2, \'Silver Account\', \'Silver Badge Visibility\', 250, 30, 5, 3, 150, 200, 20, 60, 400, 150, 15, 1, 2, ' + currentDate + ', true), (3, \'Gold Account\', \'Gold Badge Visibility\', 500, 30, 10, 6, 100, 150, 40, 40, 300, 100, 10, 1, 3, ' + currentDate + ', true), (4, \'Platinum Account\', \'Platinum Badge Visibility\', 750, 30, 15, 10, 50, 100, 60, 20, 200, 50, 10, 1, 4, ' + currentDate + ', true), (5, \'Featured Listing\', \'Highest Visibility\', 1000, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, ' + currentDate + ', true)')
            .then((accountResult) => {
              release()
              done()
            }).catch((err) => {
              console.log('exception error')
              console.log(err)
              release()
              done(err)
            })

**Comment by sehrope** [comment]
You're using the default `.toString()` of the JS Date object to build your SQL query rather. If you split out the SQL string generation and print it, you'll see that you can't execute it via psql either as it's not valid SQL. Use parameters instead: https://node-postgres.com/features/queries

Also, format your code when posting issues as it makes easier for people to read: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by RaviDavda** [comment]
Thanks **sehrope** for giving reply. As, I want to insert multiple records in a single time, then how it would be possible using parameter query. Can you give me one example of parameter query where i can insert records with an array.

**Comment by sehrope** [comment]
There are many ways to insert arrays of data into a PostgreSQL database. It even supports them natively in SQL:

```sql
CREATE TABLE foo (id text);

INSERT INTO foo
  (id)
SELECT x AS id
FROM UNNEST('{a,b,c,d,e,f,g}'::text[]) x;
```

You can execute SQL like that from JS with the array literal specified as an array parameter:

```js
const sql = `
  INSERT INTO foo
    (id)
  SELECT x AS id
  FROM UNNEST($1::text[]) x`;
const list = ['a', 'b', 'c', 'd'];
pool.query(sql, [list]).then(...)
```

In your code you can replace the `' + currentDate + '` with `$1` and then specify `[currentDate]` as the second parameter so that the `query(...)` gets invoked with parameters. So something like:

```js
const currentDate = new Date();
const sql = "INSERT INTO foo (a, b, c) VALUES ('foo', 'bar', $1)";
pool.query(sql, [currentDate]).then(...)
```

If you only want the current date you can remove the parameter entirely and use the SQL function `now()` instead to have PostgreSQL put the current timestamp there for you:

```sql
INSERT INTO foo
  (a, b, c)
VALUES
  ('foo', 'bar', now())
```

**Comment by RaviDavda** [comment]
Ya that's correct. But i want to insert multiple rows something like.

```
INSERT INTO foo 
      (a, b, c) 
VALUES 
     ('foo', 'bar', now()),
      ('foo1', 'bar1', now())
```

Now, How to do the above query with the parameters.

**Comment by sehrope** [comment]
There are lots of ways to do that. I've listed a couple options above for arrays of scalar values (i.e. text string arrays). For complicated structures that involve multiple fields you can look at using JSON to send structured data to the server.

Rather than doing any of that though it's generally easier to send multiple commands to the server, one after the other. If you need to make sure all or none of them get executed look at transaction management: https://node-postgres.com/features/transactions

**Comment by vitaly-t** [comment]
@RaviDavda check [this](https://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise) ;)
