### ISSUE TITLE
get data out of arrow function

### ISSUE THREAD

**Issue by hitgup** [brianc/node-postgres#1614]
Hi, guys!

For the first, sorry for noob-question - I'm new with JS :)

I'm getting troubles while using node-postgres and I cannot use data outside query function. I can return the data directly from the function, but when I want to use the data outside the function I get undefined

```
const user = db.query('SELECT id, username, email FROM users WHERE id= ' + userId, (err, data) => {
  if (err) {
    return err;
  }
  return data;
});

console.log(user); // undefined
```

How can I access data from function outside the function?

**Comment by brianc** [comment]
I'd recommend using `async/await` here.  Because the query responds in a callback you can't access the variable 'outside' the callback.  There should be some examples on node-postgres.com which are hopefully helpful to you.  After that you might want to google for 'node callback help' or something...this came up for me: https://blog.risingstack.com/node-js-async-best-practices-avoiding-callback-hell-node-js-at-scale/

**Comment by hitgup** [comment]
I have tried using async/await, but I got an error
> SyntaxError: await is only valid in async function

When I tried to use Promise I got Promise { <pending> }

any ideas? I know, I have to wait for the promise, but I don't know how
