### ISSUE TITLE
Select mutiples JSON columns returns a bad format QueryResult

### ISSUE THREAD

**Issue by icaaro** [brianc/node-postgres#1652]
When i'm try to select two or more JSON columns the result comes with a strange format that can't be parse or handle.
```

TABLE_X (
COLUMN JSON "A" = {
    "key": "A1",
    "value": [
        "HAAAAAAA"
    ],
    "subSchema": null
}
COLUMN JSON "B" = {
    "key": "A2",
    "value": [
        "HAAAAAAAAa"
    ],
    "subSchema": null
}
```

The QUERY i'm have made
```
await pg.query(`SELECT ("A" ,"B")
    FROM "TABLE_X" WHERE "userId"=$1`,[someID]).rows[0];
```

The result:
`{"row":"(\"{\"\"key\"\":\"\"A1\"\",\"\"value\"\":[\"\"HAAAAAAA\"\"],\"\"subSchema\"\":null}\",\"{\"\"key\"\":\"\"A2\"\",\"\"value\"\":[\"\"HAAAAAAAAa\"\"],\"\"subSchema\"\":null}\")"}`

**Comment by icaaro** [comment]
One curious thing is that when i'm select only one column, the result is totally different,
and the query result the expect.
Like this, i'm only select the column "A" that i'm describe in last post, and the result comes this.
`{"tituloProjeto":{"key":"A1","value":["HAAAAAAA"],"subSchema":null}}`

**Comment by sehrope** [comment]
The column being returned in the first query isn't JSON, it's a record of two JSON values. That's happening because the fields are wrapped in "(" ... ")". The text value of it is being returned back by the node-postgres driver. 

Here's an example of the same thing with dummy data:

```
SELECT
  t.foo,
  t.bar,
  (t.foo, t.bar)
FROM (SELECT '{"a":1}'::json AS foo, '{"a":1}'::json AS bar) t;
   foo   |   bar   |            row            
---------+---------+---------------------------
 {"a":1} | {"a":1} | ("{""a"":1}","{""a"":1}")
(1 row)
```

If there's only one value in the parentheses then it's not interpreted as a tuple as it's assumed to be a calculation. Ex: `SELECT (1)` => 1

If you want to get the data back for multiple JSON columns then remove the parentheses and return back multiple columns of data.
