### ISSUE TITLE
Single application, multiple databases, pool connection and performance issues

### ISSUE THREAD

**Issue by brandH1** [brianc/node-postgres#1664]
I am using pg version 7.4.3 and node version 4.5.0 due to dependency issues.
My application uses 27 databases (and growing) on a single postgres server. Based on request parameters I have to connect to a particular database and perform over 40 queries per request. I am running into some issues due to the max number of clients.

Is there a recommended way to have 27+ pools in a single application? I am noticing severe performance issues with more that 3 pools (2 max clients, anything more and I run into too many clients as an issue) where requests can take up to 20 seconds. I am trying to think of a solution on the application side of things if possible. 

Any help you could provide would be much appreciated.

**Comment by sehrope** [comment]
Separate databases require separate connections so you'll be limited by the overall connection limit of the cluster. Quickest solution would be bumping up the max_connections property in postgresql.conf.

If you can switch to using schemas instead of databases then you could use `SET ROLE ...` to switch between them from a common pool. It's a big "if" though as I'd imagine it'll be a lot of code / infra changes. Similarly if they're entirely separate databases you should look into moving them to separate clusters so that they have separate max_connections.

Long term your best bet would probably be to skip pooling entirely and create your own connections to each database then close it at the end of a request. Anything that involves a pool holding onto connections will eventually starve the rest of your app or anything else trying to connect to the database. Connection creation isn't *that* expensive if the latency between your server and DB is low (10-50ms). It won't be as fast as a pool and your DB would be doing extra work to create / tear them down, but it should still work and scale up to many databases as your not holding onto resources long term.

**Comment by brandH1** [comment]
sehrope, I really appreciate your answer. I will look into a solution based off of the information you provided.

**Comment by privateOmega** [comment]
@sehrope 

> If you can switch to using schemas instead of databases then you could use `SET ROLE ..`. to switch between them from a common pool. It's a big "if" though as I'd imagine it'll be a lot of code / infra changes. 

What did you exactly mean by this? I think this would be really helpful for me if you could this part a bit more in detail.

**Comment by sehrope** [comment]
@privateOmega A connection to a PostgreSQL server specifies the database to which you're connecting. While a PostgreSQL cluster (the server installation) can have multiple databases, you can't change the database once you're connected, it's fixed at connect time per client connection. You can however change the active user (i.e. "role") via `SET ROLE ...` so switching to using separate schemas (rather than separate databases) gives a similar functionality (separate namespaces for objects) while being able to reuse connections.
