### ISSUE TITLE
Pass column name as argument

### ISSUE THREAD

**Issue by richlewis14** [brianc/node-postgres#1672]
Firstly apologies if this has been asked previously..

I have a query (Update statement) wrapped in a function and will need to perform the same statement on multiple columns during the course of my script

    async function update_percentage_value(value, id){
      (async () => {
        const client = await pool.connect();
        try {
          const res = await client.query('UPDATE fixtures SET column_1_percentage = ($1) WHERE id = ($2) RETURNING *', [value, id]);
        } finally {
          client.release();
        }
      })().catch(e => console.log(e.stack))
    }

I have many columns to update and would like to be able to just call the one function, passing the column name, value and id.

Is it at all possible to do this? 

Appreciate any insight/comments you have

Thank You

**Comment by sehrope** [comment]
No column names are identifiers and they can't be specified as parameters. They have to be included in the text of the SQL command.

It is possible but you have to build the SQL text with the column names. If you're going to dynamically build SQL you should make sure to escape the components using something like pg-format or use an ORM that handles this type of thing.

So something like:

```js
const format = require('pg-format');

async function updateFixtures(id, column, value) {
  const sql = format('UPDATE fixtures SET %I = $1 WHERE id = $2', column);
  await pool.query(sql, [value, id]);
}
```

Also if you're doing multiple updates to the same row back-to-back then you're likely better off with a single `UPDATE` statement that modifies all the columns rather than separate statements as they'd be both slower and generate more WAL on the server.

**Comment by richlewis14** [comment]
Thank you for your help, works how I was expecting..I will look into a batch update, refactoring my code in stages that I understand..  Speaking of which, does my function need the try/catch or can i just use the await... Wanted to catch and log out errors if needed..Thanks again for your help

**Comment by sehrope** [comment]
You only need the try/catch if you're going to do manual resource cleanup. If you use `pool.query(...)` there's nothing to clean up so it's not necessary. If you manually create a `Client` and connect it then you'd need a try / catch / finally block around it to make sure the connection is closed. The `pool.query(...)` approach is generally easier and the preferred approach if it's usable (ex: transactions require manually managing connections but one-off SQL doesn't).

**Comment by lmf-git** [comment]
This doesn't work. "There is no parameter 2"

**Comment by charmander** [comment]
@lmf-git You’ve probably made a mistake in applying it somehow. Hard to say without seeing any code.
