### ISSUE TITLE
Never release idle connection

### ISSUE THREAD

**Issue by celsomarques** [brianc/node-postgres#1673]
Hi,

First of all, thanks for the excellent job you done here!
I'm investigating an issue on my side regards to connection pool. I'm executing a very simple queries and all of them keeps the connection in idle until time outs.

Is this the expected behavior or it should release connection to the pool after query ends?

Thank you!

EDIT 1:

If I don't call `client.release(true)` the system cannot reuse the idle connections and stopped processing messages.

**Comment by sehrope** [comment]
Yes it's normal behavior. The default behavior of the pool is to keep connections open for 30-seconds after use so that subsequent usage is fast. After 30-seconds of inactivity pool connections will be closed. 

If you're experiencing an issue with connections not being closed, not being removed after inactivity, or `pool.query(...)` not returning the connections to the pool then please put together a complete example that reproduces the issue. Make sure to include your node version and node-postgres version as well.

**Comment by celsomarques** [comment]
Hi @sehrope ,

Thanks for the quick reply.
I'll try to create a project that reproduces the issue but in the meantime, just for clarification, if I don't call client.release(true) the system don't reuse the idle connections and stopped processing messages.

Node vesion: 8.11.1
node-postgres: 7.4.3
Postgres version: 9.5.4

**Comment by celsomarques** [comment]
It was my fault. Sorry for bother you and thanks.
