### ISSUE TITLE
Can someone please tell me where are the error codes?

### ISSUE THREAD

**Issue by demian85** [brianc/node-postgres#1697]
Hello,

I'm finding this a bit disturbing. I went over all the documentation from pg and pg-promise but cannot find a reference to error codes, and sounds a bit weird.

I just want to know when a query fails because of a duplicate key error. How an I achieve that? Am I asking too much?

I'm using `pg-promise` and all I can see is this http://vitaly-t.github.io/pg-promise/errors.QueryResultError.html

No idea what the code is, seems hardcoded 😕 

Thanks.

**Comment by charmander** [comment]
https://www.postgresql.org/docs/current/static/errcodes-appendix.html

**Comment by vitaly-t** [comment]
@demian85 You misunderstand, the nature of [QueryErrorCode](http://vitaly-t.github.io/pg-promise/errors.QueryResultError.html) is to signal when the number of expected records doesn't match what you have requested, as explained in the API. As such, it is a library-level error, not server-level, that's why its field `code` refers to the error detail. I believe the API gives you the full description of what it is. Please read it :wink:

**Comment by demian85** [comment]
Okay thanks, so any error thrown in a query-related method will contain the
code property with the standard PG error code?
It'd be nice to clarify that in the docs.
Thanks!

**Comment by vitaly-t** [comment]
@demian85 Not sure what you mean by standard PG error code. In your case `code` is of type [queryResultCode](http://vitaly-t.github.io/pg-promise/errors.html#.queryResultErrorCode), as explained.
