### ISSUE TITLE
How about using ?, ? instead of $1, $2, ...

### ISSUE THREAD

**Issue by devingao-df** [brianc/node-postgres#1720]
I don't know how many parameters it will actually have. Dynamic parameters count.

**Comment by sehrope** [comment]
The driver uses $1, $2, ... etc because that's how the backend expects parameters to be represented in SQL.

There's plenty of helper modules that provide alternative methods of supplying parameters. Check out the "Extras" section of the wiki (https://github.com/brianc/node-postgres/wiki/Extras). You should look for one that provides "named parameters" as it'll probably do what you want.

Alternatively, you can handle this kind of thing with numbered parameters with something like this:

```js
const params = [];
const whereClauses = [];
if (opts.name) {
    params.push(opts.name);
    whereClauses.push(`t.name = $${params.length}`);
}
if (opts.color) {
    params.push(opts.color);
    whereClauses.push(`t.color = $${params.length}`);
}
// ... etc
const sql = `
  SELECT t.*
  FROM foobar t
  ${whereClauses.length === 0
    ? ''
    : 'WHERE ' + whereClauses.join('\n  AND ')}`;
return pool.query(sql, params);
```

*(Not actually tested but hopefully you get the general idea)*

**Comment by brianc** [comment]
Postgres protocol doesnt support question mark parameter placeholders. You
can use a higher level library to do that if you want, but this libs
responsibility is not prsing query text and doing substitutes.
