### ISSUE TITLE
Error: Connection Teriminated

### ISSUE THREAD

**Issue by ajaygr8** [brianc/node-postgres#1837]
Getting " Error: Connection Terminated" for below mentioned SQL while connecting with postgress.
Kindly let me know if there is a syntax issue with the select query

console.log(q);

            client.query(
                    "SELECT username FROM "+"\"user\""+" WHERE "+" userid "+" = "+" 1234 ",
                    function(err, result) {
                        if (err) {
                            console.log("entered error");
                            console.log(err);
                            callback('');
                        } else {
                            console.log(result.rows);
                            callback(result.rows);

**Comment by klvenky** [comment]
@ajaygr8 I don't find anything wrong with that. Can u give us little more information on the same.

**Comment by sirisian** [comment]
A really common cause for this is calling client.end() when a query is still running. In modern code with async/await this is caused by forgetting to await on the client.query (or say the async function it's inside of is used without await) such that a following client.end() call preempts the query. I'm just adding this comment in case someone finds this.
