### ISSUE TITLE
Should break loop once `useBinary` is true.

### ISSUE THREAD

**Issue by CreativeCactus** [brianc/node-postgres#1875]
https://github.com/brianc/node-postgres/blob/6b8176e841584b76bcbd1972bf95e50558ba7395/lib/connection.js#L269

This will save a bit of time. You could write the line as:

`for (var j = 0; j < len; j++) { if(useBinary |= values[j] instanceof Buffer) break; }`

**Comment by CreativeCactus** [comment]
Was able to run tests and get up to 

```
***Testing connection***
(node:79801) UnhandledPromiseRejectionWarning: error: password authentication failed for user "user"
```

Could not quickly find any `.md` on how to run these tests and am in a hurry, so here's the mentioned change, partially tested. Cannot add any testing for as the fix is performance based.

**Comment by CreativeCactus** [comment]
https://github.com/CreativeCactus/node-postgres/blob/master/lib/connection.js#L270

**Comment by boromisp** [comment]
To run the tests you need a PostgreSQL database, and provide the connection parameters as [environment variables](https://www.postgresql.org/docs/current/libpq-envars.html). Example: `PGUSER=postgres PGDATABASE=postgres npm run test`

**Comment by charmander** [comment]
I don’t think this improvement would be noticed (happy to see a practical benchmark saying otherwise, of course). `const useBinary = values.some(Buffer.isBuffer)` might be a readability improvement.

The relevant code is here now, by the way: https://github.com/brianc/node-postgres/blob/d7b22b390d355798d8204787f6b122d15c30995b/packages/pg-protocol/src/serializer.ts#L119-L123
