### ISSUE TITLE
Cant add parameters in dblink with format function

### ISSUE THREAD

**Issue by LinoAlejandro** [brianc/node-postgres#1885]
I am currently trying to execute a dblink function like this:

let query = 
    `SELECT
        someColumns
    FROM (
        SELECT 
            * 
        FROM 
            dblink (
                \'DataConection\', 
                format(
                    \'SELECT 
                        someColumns
                    FROM 
                        someTable 
                    WHERE
                        someColumn ilike ''%s''
                    LIMIT 
                        %s
                    OFFSET 
                        %s
                    \',
                    $1,
                    $2,
                    $3,
                )
            ) as data1 (
                someColumns someType
            )
    ) as data2 `

let params = [
    '%' + req.query.busqueda + '%',
    req.query.limit,
    req.query.offset,
]

pool.query(query, params)

but it is returning the next error:

{"stack":"error: could not determine data type of parameter $1\n    at Connection.parseE (/Users/datateam/Documents/workspace-update/SearchServer/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/Users/datateam/Documents/workspace-update/SearchServer/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/Users/datateam/Documents/workspace-update/SearchServer/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:197:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)","message":"could not determine data type of parameter $1","name":"error","length":111,"severity":"ERROR","code":"42P18","file":"postgres.c","line":"1359","routine":"exec_parse_message"}

i have manually check the query an there is no problem with it; i have changed positions, format and datatype of the parameters; as well as changing the number of simple commas in the format string to something like '''%s''' or ''''%s''''; all whitout success

**Comment by sehrope** [comment]
Format your code example with backticks so its easier to read. More info on formatting options is here: https://github.github.com/gfm/#fenced-code-blocks

That error is coming from the server because it cannot infer the data type of the parameter. Usually the backend can infer the data type from the usage (e.g. figure it's "text", "int8", "timestamptz") but as `format(...)` can take any parameter type, it cannot in this case.

You can work around this by adding casts to the parameter references. You should also use `%L` for the like expression so that any quotes are properly escaped:

```sql
SELECT format('SELECT someColumns FROM someTable WHERE someColumn ILIKE %L LIMIT %s OFFSET %s',
          $1::text,
          $2::int,
          $3::int)
```

If you're pulling the `limit` and `offset` values from an HTTP request then you should also ensure that they're integers prior to sending them to the DB query. By default the values in something like express will be a string. With the proper casts in place the DB should give you an error but better to reject the request entirely before you get to that point.

**Comment by LinoAlejandro** [comment]
Thanks a lot for the recommendations and for the solution sehrope, all working fine now

**Comment by LinoAlejandro** [comment]
`select * from somewhere`
