### ISSUE TITLE
small query

### ISSUE THREAD

**Issue by sachincloudnaut** [brianc/node-postgres#1941]
Hello Brian,

I am using "pg" NPM package to connect to AWS Redshift db it works fine.

My co-worker said that my Node app (which is using "pg" package) also needs support of Java runtime and JDBC/ODBC driver on the computer where Node app is running. This is because "pg" could be a wrapper around JDBC or ODBC drivers. Please let me know if that is correct. Is NPM package "pg" depends on these external software?

**Comment by charmander** [comment]
What your coworker said is not correct. pg is its own driver and doesn’t wrap any Java libraries (Java and JavaScript are mostly unrelated too). pg-native (used when you access `require('pg').native` instead of the pure-JavaScript client `require('pg')`), however, wraps a set of bindings to libpq, so if you use it you’ll need libpq installed. Still unrelated to JDBC.
