### ISSUE TITLE
Add fieldNameMap to allow camelcase results.

### ISSUE THREAD

**Issue by thebinarysearchtree** [brianc/node-postgres#1962]
Postgres only has lowercase column names unless you put everything in quotes. node-postgres returns an array of objects. These objects will therefore all have lowercase property names despite the convention in javascript for camelcase.

Mapping the returned array to a new array is a waste of resources. I think it would be a good idea to have a configuration option for the driver so that you can input a map, such as:

`{  'userid': 'userId', 'refreshtoken': 'refreshToken'  }`

Which would then be used in result.js to make a new fields array:

`var field = this.fields[i].name`

to allow the returned objects to respect the naming convention of the programming language instead of the database and prevent bugs.

**Comment by vitaly-t** [comment]
> Mapping the returned array to a new array is a waste of resources

That's an exaggeration. Any data remapping in JavaScript usually involves creating a new array.

> it would be a good idea to have a configuration option for the driver so that you can input a map, such as...

It would not be a good idea, because it would depend on the database complexity, which only the application knows about, and not the driver.

> to allow the returned objects to respect the naming convention of the programming language

This should be managed by your own application. The only thing a driver should offer you is the ability to intercept data receiving, so it can be remapped before it reaches the client.

For example, [pg-promise](https://github.com/vitaly-t/pg-promise) has always had this feature. See [this article](https://coderwall.com/p/irklcq/pg-promise-and-case-sensitivity-in-column-names).

**Comment by thebinarysearchtree** [comment]
If we can create custom types that map from Postgres types to javascript types, there is no reason we shouldn't be able to map from Postgres naming convention of columns to javascript naming convention of properties.

**Comment by calebboyd** [comment]
@thebinarysearchtree you can do what you want using the `.connection` object on the `pg.Client` class
You only want to do this once per connection -- you can memoize or improve efficiency however you like

```javascript
  const { Pool } = require('pg')
  const camelCase = require('lodash.camelcase')
  const pool = new Pool({ connectionString })
  pool.on('connect', (client: any) => {
    //use the connection to alter the rowDescription for your query
    client.connection.on('rowDescription', (msg) => {
      for (const field of msg.fields) {
        field.name = camelCase(field.name)
      }
      client.activeQuery.handleRowDescription(msg)
    })
  })
```

**Comment by brianc** [comment]
I wouldn't recommend reaching into the client & grabbing the `connection` - I'm thinking I might need to deprecate that object depending on how my performance work turns out.  I think the right way to map fields to custom names is in the query directly, a module _on top of `pg`_, or in your own application code.  I have no plans to add this to the library itself.
