### ISSUE TITLE
pool.end() getting stuck

### ISSUE THREAD

**Issue by AxelTerizaki** [brianc/node-postgres#1988]
Hello.

I've searched through the issues and found that #1670 and #1802 were helpful in understanding how pool.end() worked, but I have an issue nonetheless.

My app is a standalone nodeJS app that launches a PostgreSQL binary and then connects to it using node-postgres.

My code is basically as follows :
```JS
database = new Pool(dbConfig);
await database.connect();

export function db() {
	return database;
}
```

I call my queries with db().query() in other parts of my app.

So far, so good.

However, my app has to quit at some point, and I need to properly close the PostgreSQL binary.

If I use `await database.end()` before killing postgres (via `pg_ctl stop`) my app gets stuck as if it was waiting for some connection to end... but I don't see which, as there seems to be no connection running.

If I don't use `await database.end()`, postgres terminates successfully but for some reason I get the following PG error from node-postgres : "terminating connection due to administrator command"

Is there a way I could properly shut down all connections of a `pool` before shutting down Postgres without triggering any errors ?

Thanks in advance for your help.

**Comment by sehrope** [comment]
> My code is basically as follows :
> 
> ```js
> database = new Pool(dbConfig);
> await database.connect();
> 
> export function db() {
> 	return database;
> }
> ```
> 
> I call my queries with db().query() in other parts of my app.

The function (`Pool.connect()`) returns a connected client. The `database.connect()` call is instructing the pool to create a new connection and waiting for it to connect, but you're not saving the client. So the pool thinks there's a connection in use that is not referenced anywhere your app and never shut down.

The rest of your code is using the `query(...)` on the pool, not your one client. Each spot that is executing a query is either reusing a cached pooled connection or creating a new one on demand (up to the pool max).

> If I use await database.end() before killing postgres (via pg_ctl stop) my app gets stuck as if it was waiting for some connection to end... but I don't see which, as there seems to be no connection running.

It's the connection created via the `await database.connect()` line. It's a dangling reference with an open socket to the backend.

> If I don't use await database.end(), postgres terminates successfully but for some reason I get the following PG error from node-postgres : "terminating connection due to administrator command"

When the PG server shuts down it sends out an error notice to connected clients to close gracefully. The node-postgres driver translates those to events on the client. There's no default handler for these messages on a client so the default action is for node to crash as it receives an unhandled `error` event.

> Is there a way I could properly shut down all connections of a pool before shutting down Postgres without triggering any errors ?

Get rid of the extract `await database.connect()`. It's not needed as everything you're doing is using the pool which manages it's own connect calls internally. Then make sure that your done with all your actual work in the program and end the pool. As long as your pool usage is only via `pool.query(...)` it should not have dangling resources after `pool.end()` is called.

If you just want your app to exit then you can also do `process.exit(0)`. That will close *all* sockets as the process will exit. The PG server will handle the socket closing just fine. It's common to have an explicit exit call at the end of a nodejs program as otherwise there could be unrelated things forever polling on the event loop (ex: like a pool that's not shutdown).

**Comment by AxelTerizaki** [comment]
I had no idea I didn't need `database.connect()`. I thought it was needed so the pool establishes a connection to the database, so it's the `new Pool` that does the trick...

I'll try it out and report on how it worked out, thanks for the pointer.

**Comment by AxelTerizaki** [comment]
Looks like it solved my problem, after doing a few tests. Thanks again for your feedback, that was very helpful.

I'll close the issue then. :)
