### ISSUE TITLE
Update client data and reconnect or create a new client?

### ISSUE THREAD

**Issue by pekkalaaksonen** [brianc/node-postgres#2037]
I am writing an application where I need to first check if a database exists and if not create it. Then I need to check if needed tables exist in that database.

For this purpose I need to first connect to "maintenance" database, e.g. default postgres database, and then connect to actual database and create tables there if needed. Can I update the initial client I used for first connection or do I need to create a new client and use that?

**Comment by joelmukuthu** [comment]
Hi, Postgres doesn’t support switching databases like that and neither does this driver. psql has a `\c database_name` command but that actually closes your current connection and opens a new one.

I assume you’ll need to be creating or altering tables frequently, and that’s commonly referred to as “running database migrations”. You can google around for a library that will help with handling that.

Regardless of the library though, you’ll need to orchestrate it with two Pool instances, where you use one to create the database and tables (and then `pool.destroy` it because it won’t be needed anymore) and the other to connect to the newly created database and run with your application. I’m also assuming the application is an API server created with ExpressJs or something like that.

I would also recommend running the first part as a separate script that runs once and exits and is independent of your application, even with a different Postgres user so you can assign them different database permissions. That makes things a bit more tricky since you run migrations without stopping and restarting your application but is better in the long run as it forces you to decouple them and write ideally zero-downtime migrations.

**Comment by pekkalaaksonen** [comment]
@joelmukuthu Ok, thanks!
