### ISSUE TITLE
error: time zone "gmt-0500" not recognized

### ISSUE THREAD

**Issue by han-so1omon** [brianc/node-postgres#2061]
I am doing a simple `INSERT INTO` query. The database column in question is of type `TIMESTAMPTZ`. Here is my code segment:

```
let date_created = Date();

const res = await db.query(
  `INSERT INTO testtable1 (date_created
   VALUES ('${date_created}')`
);
```

Which produces an error:
`time zone "gmt-0500" not recognized`

**Comment by brianc** [comment]
it looks like you might be concatenating a raw date value into your query.  You mean to be doing that? e.g. what happens if you do this:

```js
console.log(`INSERT INTO testtable1 (date_created
VALUES ('${date_created}')`);
```
? 

I don't think you want to be inserting dates that way.  You should try this:

```js
const res = await db.query('insert into testtable1 (date_created) VALUES ($1)', [date_created])
```

Basically, use [parameterized queries](https://node-postgres.com/features/queries#Parameterized%20query).

**Comment by han-so1omon** [comment]
So I have tried
```
const res = await db.query('insert into testtable1 (date_created) VALUES ($1)', [date_created])
```

This yields: `SyntaxError: Invalid or unexpected token`

That error goes away when using \` instead of \'

So I tried the following:
```
const res = await db.query('insert into testtable1 (date_created) VALUES ($1)', [date_created])
```

This yields the original error: `time zone "gmt-0500" not recognized`

This is all with postgresql-12 on CentOS Stream

**Comment by brianc** [comment]
yeah that seems weird - i can take a look for you but can you include an _entirely_ self-contained block of code that reproduces the problem? that includes creating any temp tables or anything needed? I should be able to copy/paste your code into a `test.js` file and run `node test.js` and see the failure.  Don't need to include connection params...I have a test environment I use which has them pre-defined as environment variables so leave them blank/default please. 🙏

**Comment by han-so1omon** [comment]
Sure. I have also found that using `new Date()` instead of `Date()` works, which you probably knew about. Here is the code:

```
(async () => {
  const res1 = await db.query(
    `
    CREATE TABLE IF NOT EXISTS testtable (
    uid SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    email VARCHAR(255) UNIQUE,
    email_verified BOOLEAN,
    date_created TIMESTAMPTZ,
    last_login TIMESTAMPTZ,
    password VARCHAR(255) NOT NULL
    )
    `
  );
  let tables = {users: 'testtable'};
  let date_created = Date();
  let last_login = Date();
  let query2 = {
  text: '
    INSERT INTO $1
      (uid, username, email, email_verified, date_created, last_login, password)
    VALUES ($2, $3, $4, $5, $6, $7, $8)
    '
  values:
    [tables.users, 0, 'a', 'a@a.com', false, date_created, last_login, 'a']
  };
  const res2 = db.query(query2);
})();
```

**Comment by charmander** [comment]
`Date()` returns a string. To create a `Date` object, you need `new Date()`.

**Comment by joelmukuthu** [comment]
And also, identifiers (table names, column names) cannot be parameterized in an SQL query, so your `query2` should be something like:

```js
let query2 = {
  text: `
    INSERT INTO "${tables.users}"
      (uid, username, email, email_verified, date_created, last_login, password)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
  `,
  values:
    [0, 'a', 'a@a.com', false, date_created, last_login, 'a']
  };
```

Or simply `INSERT INTO "testtable"`, instead of using a variable. The key thing here is that you don't use a placeholder for it; the same way you don't use placeholders for the column names.

Note that, with this way of building up a query, `tables.users` should never be accepted as user input (e.g. from the POST body of an HTTP request). If it is user input, you'll have to do more a lot more to guard against SQL injection. For example, with the query I've provided, an attacker could do something like this to delete all the data in the table:

```js
const tables = { 
  users: 'testtable" (uid) values (1);delete from testtable;insert into "testtable' 
};
const query = { text: `INSERT INTO "${tables.users}" ...`
```

**Comment by proxybee** [comment]
It has been a while hence this might have been sorted but I will just drop this for anyone else that might need it or come across this later: Since you already use a timestamp in the database you don't need to include it in the insert it will be entered automatically when the user is saved. for instance based on the testable above:

```
(async () => {
  const res1 = await db.query(
    `
    CREATE TABLE IF NOT EXISTS testtable (
    uid SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    email VARCHAR(255) UNIQUE,
    email_verified BOOLEAN,
    date_created TIMESTAMPTZ,
    last_login TIMESTAMPTZ,
    password VARCHAR(255) NOT NULL
    )
    `
  );
  let tables = {users: 'testtable'};
  let query2 = {
  text: '
    INSERT INTO $1
      (uid, username, email, email_verified, last_login, password)
    VALUES ($1, $2, $3, $4, $5, $6)
    '
  values:
    [tables.users, 0, 'a', 'a@a.com', false, last_login, 'a']
  };
  const res2 = db.query(query2);
})();
