### ISSUE TITLE
Pause reading from cursor if readable stream is paused

### ISSUE THREAD

**Issue by jestepseamless** [brianc/node-postgres#2135]
Hi there!

In pg-query-stream, is there anyway to "pause" the cursor read if the readable stream is paused? Or is there a way to temporarily stop reading from the cursor if the internal buffer of the readable stream gets too big?

**Comment by brianc** [comment]
yah absolutely - that's how it works so using the `.pause()` and `.resume()` methods on the pg-query-stream instance will stop the cursor from reading as well.  Due to node streaming behavior there's a little bit of a buffer kept in the stream so `.pause()` may not _instantly_ stop the cursor from reading.  The internal buffer already puts back pressure on the cursor so you wont end up buffering like 1,000,000 rows into memory, even if you do a `select *` from a huge table & stream the results.

**Comment by brianc** [comment]
In general `pg-query-stream` should behave as you would expect from any other readable stream in node....including back-pressure, the `readable` event, buffering, etc... If you see behavior where you stream is reading continuously even though you've paused it please open an issue w/ steps to reproduce & I'll take a look!
