### ISSUE TITLE
Recommended way of handling ECONNRESET?

### ISSUE THREAD

**Issue by AdityaAnand1** [brianc/node-postgres#2162]
The use case is having multiple/long running queries on my local machine, which, if I leave the machine, the connection is broken, the machine goes to sleep and the script stops.

I'd like to simply have the script continue whenever it gets the connection back rather than throwing. Is there a way to do this?

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Client instance at:
    at Connection.connectedErrorHandler (C:\Projects\p\node_modules\pg\lib\client.js:202:10)
    at Connection.emit (events.js:315:20)
    at Socket.reportStreamError (C:\Projects\p\node_modules\pg\lib\connection.js:73:10)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by brianc** [comment]
you could catch the error on the client:

```
client.on('error', (e) => {
  if (e.code == 'ECONNRESET') // do something about ECONNRESET here
})

```

Handling async network errors like this is a bit non-trivial, so you'll prolly have to work through it a bit on your side, but the client should emit these errors.  If the client _doesn't_ emit an error & throws something uncatchable...that's def an issue w/ `pg`.  otherwise it's just a kinda tricky problem you'll have to solve in your own app or from another npm module that has either generic or `pg` specific reconnection handling for sockets.

Hope this helps & good luck!
