### ISSUE TITLE
Question regarding result.rowCount

### ISSUE THREAD

**Issue by MelissaSnell** [brianc/node-postgres#2182]
Hi there

I just wanted to clarify something in the documentation.

On this page for the Result object you say that rowCount is not set for the number of rows returned from a query. 

I am finding that for a pool.query, rowCount does seem to be > 0 if result.rows.length>0.

Does rowCount reflect the number of rows returned for a pool.query but not for a client.query?

Many thanks in advance.

**Comment by sehrope** [comment]
The `rowCount` is populated from the command tag supplied by the PostgreSQL server. It's generally of the form: `COMMAND [OID] [ROWS]`

Here's the piece of pg that parses the value into the `rowCount` field: https://github.com/brianc/node-postgres/blob/35328807e3612cb267bee86dccb2551ad186624a/packages/pg/lib/result.js#L42-L52

For DML commands (INSERT, UPDATE, etc), it reflects how many rows the server modified to process the command. For SELECT or COPY commands it reflects how many rows were retrieved or copied. More info on the specifics here: https://www.postgresql.org/docs/current/protocol-message-formats.html (search for CommandComplete for the message type)

The note in the docs about the difference is because that value is controlled by the server. It's possible for a non-standard server (ex: PostgreSQL fork) or a server version in the future to provide different information in some situations so it'd be best not to rely on it to assume that the rows array length matches the `rowCount`. It's fine to use it for DML counts though.

**Comment by MelissaSnell** [comment]
Many thanks for the explanation. Much appreciated

**Comment by brianc** [comment]
holy smokes this description is great - mind if I add it to the docs w/ credit @sehrope ?

**Comment by sehrope** [comment]
Thanks! Sure go for it!
