### ISSUE TITLE
Bad request in transaction locks and doesn't throw error

### ISSUE THREAD

**Issue by johnovalle** [brianc/node-postgres#2231]
I'm trying to do a transaction as the second insert depends on the result of the first insert.
I found this example code for setting a transaction and it works great if the data is valid.

```
export const tx = async (callback: TransactionFunction) => {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    try {
      await callback(client);
      client.query('COMMIT');
    } catch (e) {
      client.query('ROLLBACK');
    }
  } finally {
    client.release();
  }
};
```

Inside the callback I'm calling this function to make the query:
```
async function transactionQuery(client: PoolClient, text: string) {
    return client.query(text);
}
```

If the data is bad for any reason, a bad enum, duplicate unique field, null for a field that requires a value etc. The request never finishes. No errors are returned. When not doing a transaction errors come back just fine.  Maybe I'm just missing something, thank you.

I'm using `"pg": "^8.1.0"`

**Comment by sehrope** [comment]
The COMMIT and ROLLBACK commands need to be awaited to ensure they actually complete. Otherwise the client would be returned to the pool prematurely.
 
See here for an example of how to create a transaction wrapper that accepts a task: https://github.com/sehrope/postgres-with-nodejs-code/blob/master/src/00022-transaction-helper-sequential.js#L9-L35

That example also handles returning cleanly ROLLBACKed clients back to the pool if it's a transient user level SQL error (ex: duplicate key) vs an unrecoverable permanent one (ex: server backend was killed).

**Comment by johnovalle** [comment]
It's not even getting to the COMMIT and ROLLBACK commands, they aren't even being called.  (Your point about them needing to be awaited is well taken and that has been added with the same results)
The query which is being awaited never finishes. 
```
const result =  await transactionQuery(client,  `INSERT INTO users(email, password, type) VALUES('${email}', '${hash}', '${type}') RETURNING id, email, type, admin, date_created`)
// It never gets here if there is any kind of error, this never resolves. 
console.log(result)
```

**Comment by johnovalle** [comment]
After investigating further it looks the error was getting swallowed up by another piece of code.
