### ISSUE TITLE
Question: How to improve multi-query performance

### ISSUE THREAD

**Issue by cphillips** [brianc/node-postgres#2311]
In reading the documentation, I understood the code below won't actually give me concurrency because the client will queue the queries and execute them one at a time. First I want to make sure I understood that correctly, and second I want to know what the options are when I don't care about execution order, but I do care about all the queries running concurrently and all succeeding.

```js
export async function writeDb(data: any) {
  const queries = toQueries(data)
  const client = await pool.connect()

  try {
    await client.query('BEGIN')

    const pending = []
    for (const query of queries)
      pending.push(client.query(query.sql))

    await Promise.all(pending)
    await client.query('COMMIT')
  } catch (e) {
    await client.query('ROLLBACK')
    throw e
  } finally {
    client.release()
  }

}
```

**Comment by sehrope** [comment]
A client has an internal queue but you're better off not relying on it. With transactions in particular it can get messy.

SQL commands during a transaction are inherently sequential and if one fails you usually do not want to attempt any subsequent commands to be attempted outside of rolling back. Also, the PostgreSQL server won't let you execute them anyway as any command other than ROLLBACK will be rejected with an error.

There's no way to concurrently run SQL commands in the same transaction. The server has no concept of it as it processes one command at a time. Any concurrency would need to be across separate connections (and thus separate transactions). So you should await each query as you loop through it..

Also, there's some edge cases to handle with discarding bad connections from the pool if the connection has been terminated or otherwise not usable after a rollback. Otherwise you'll keep adding back the bad connection to the pool as it relies on the user to instruct the pool that the connection is no longer valid.

```js
export async function writeDb(data: any) {
  const queries = toQueries(data)
  const client = await pool.connect()

  try {
    await client.query('BEGIN')
    for (const query of queries) {
      await client.query(query.sql)
    }
    await client.query('COMMIT')
    client.release() // success so return client to pool for reuse
  } catch (e) {
    try {
      await client.query('ROLLBACK')
      client.release() /// rollback success so return client to pool for reuse
    } catch (rollbackErr) {
      client.release(rollbackErr) // truthy arg instructs pool to discard the connection
    }
    throw e // throw original error
  }
}
```
