### ISSUE TITLE
Losing connections in pg_pool?

### ISSUE THREAD

**Issue by pcbentz** [brianc/node-postgres#2366]
Greetings,

I am running 30 nodejs instances in AWS talking to a postgreSQL rds instance.  Each nodejs instance is using pg and a pg_pool for all database interaction.  All calls are using simply pg_pool.query to interact with the pool. 

Everything runs along well for several hours - we watch the waitingCount, idleCount and runningCount during execution and the values rise and fall nicely during the run.

As some point in time however things go off the rails.  The totalCount rises to the limit of 90, the idleCount remains at zero and the waitingCount continues to rise. (up to and over 100,000).

The netstat command on the ec2 instances show they have 90 sessions established to the database server - however pg_stat_activity on the postgreSQL server indicates no queries are active from the instance.

It appears the connections are idle - however the pool does not seem to be placing them back into the pool for the waiting entries?

NodeJS Version: 4.2.6
pg Version: 6.4.2
pg-pool: 2.0.10
PostgreSQL Version 9.5.15
RDS instance size: db.r4.16xlarge

We are creating a single global pool - and are handling error, remove, connect and aquire messages.  
Have the pool configured with an connectionTimeoutMillis: 60000 and idleTimeoutMillis: 120000
Using the bluebird promise.

Am I actually losing connections in the pool?    

As an aside - eventually the postgreSQL rds instance eventually runs out of freeableMemory and crashes.  AWS claims the crash is caused by excessive load.

**Comment by charmander** [comment]
You should upgrade to a supported version of Node and a supported version of pg.

**Comment by brianc** [comment]
@pcbentz - charmander is right you're running pretty old stuff.  It's hard to say if the bugs are related to your code, version of node, or older version of PG....a few things I can recommend, some of which you probably already thought of.

Make sure you have a single place in your app to do queries & make sure all the clients are returned to the pool...the most common issue of starved connection pools is not returning the client to the pool. [At the very bottom of this page](https://node-postgres.com/guides/project-structure#example) I put a little bit of info on how you could possibly track down unreturned clients.  



> As an aside - eventually the postgreSQL rds instance eventually runs out of freeableMemory and crashes. AWS claims the crash is caused by excessive load.

If your instance is running out of memory but your sessions connected to the database is remaining steady at 90 then it's likely something fishy going on with your actual database.  Connections to postgres backend use a non-trivial amount of ram because postgres uses a threaded model - but it's something like 4 megabytes per connection.  In the distant past I've crashed a postgres instance on an 4xl instance in ec2 but we connected like 3,000+ connections to it at once (oops!).  Anyways, if you only have 90 connections steadily open to your database and it's running out of freeable memory, something else is going on there...possibly some runaway query or something else on the box.

The final thing you can try doing, if upgrading pg & node isn't an option for you (I run apps in prod too, I know it can be a pain) is using something like https://www.npmjs.com/package/generic-pool and implement your own pool if you suspect the issue is in pg-pool.  You can have fine-grained control over acquire and release semantics there & do any sort of instrumentation you need.

Hope this helps!
