### ISSUE TITLE
Relation schema.func() does not exist

### ISSUE THREAD

**Issue by TLKG** [brianc/node-postgres#2478]
Using pg aka node-postgres v8.3

I have a PostgreSQL function named `f()` under `myshema`. It is verified has permission and runs perfectly in pgAdmin 4.25 as

`select * from myschema.f()`

Calling it in Node (v11):
```
const Pool = require("pg").Pool;
const pool = new Pool(
    {
        user: ...,
    }
);
const pgCallF = (paramless, cbFunc) =>
{
    var sql = 'select * from "myschema"."f()"'; // same err if myschema.f(), but ok for query like 'select * from myschema.table1'
    pool.query(sql)
        .then
        (
            good =>{...},
            bad =>{...}
        )
        .catch(error => {
            console.log(error);
            next();
        })
}
```
Issue is also reported at [SO](https://stackoverflow.com/questions/66342388/relation-schema-f-does-not-exist-from-node-postgres)

**Comment by charmander** [comment]
`"myschema"."f()"` definitely isn’t right; the parentheses for a call go outside the quotes that delimit an identifier. With quotes, it should be written `"myschema"."f"()`. I’m surprised that there’s the “same err if myschema.f(),” though – are you sure it’s the same error and not just a similar one, like “**function** myschema.f()  does not exist” instead of “relation”?

Also, it’s not the problem here, but I really recommend not using Node 11 if you can help it – it’s long since EOL. pg 8.x supports both Node 10 and Node 12 for a non-EOL Node in either direction.

**Comment by TLKG** [comment]
Thanks for the quick response and suggestion on Node 11. I've figured it out the correct way is to 
`select * from myschema.f();`. 

- no quotes needed.
- append a `;`
