### ISSUE TITLE
Notify event casesensitivity not working

### ISSUE THREAD

**Issue by atpakam** [brianc/node-postgres#2543]
When sending a notification event like `NOTIFY testCase` while having a connection open on `LISTEN testCase` the callback will never be called.
However, when sending 'NOTIFY testcase' the callback will be called.

Here's a sample (modified from https://node-postgres.com/api/client#events ):
```
const client = new pg.Client()
client.connect()
client.query('LISTEN testCase')
client.on('notification', msg => {
  console.log('I got that')
})
client.query('NOTIFY testCase') // will not work
client.query('NOTIFY testcase') // works
```

**Comment by atpakam** [comment]
I'm running PostgreSQL 12.2 on x86_64-pc-linux-gnu and using "pg": "^8.6.0"
My setup is using `import { Pool } from 'pg'` as well as transactions (I am performing `BEGIN` and `COMMIT` around the notify statement)
As for the trigger, I've tested it via pgAdmin -> `SELECT pg_notify('testCase', 'payload');` as my events come from a different application performing `pg_notify`
I've tested the following channel
`pg_notify` -> `Node.JS`
`abc` -> `abc` works
`aBc` -> `aBc` doesn't work
`abc` -> `aBc` works
`a_c` -> `a_c` works

**Comment by charmander** [comment]
Okay, so the real code uses `pg_notify`, which takes a `text` value instead of an identifier. [`LISTEN` takes an identifier](https://www.postgresql.org/docs/current/sql-listen.html#id-1.9.3.153.6), which [will be lowercased if not quoted](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS). You need:

```sql
LISTEN "testCase"
```
