### ISSUE TITLE
How to obtain parameterized SQL statements？

### ISSUE THREAD

**Issue by lwq057** [brianc/node-postgres#2623]
```
pool.query("INSERT INTO message (uid,aid) VALUES ($1,$2);",[111,222]);
```

How to get SQL：

```
INSERT INTO message (uid,aid) VALUES (111,222);
```

Do not execute, return SQL statement。

**Comment by brianc** [comment]
This isn't handled by this library because this is not how postgresql parameterize statements work.  The parameters and statement text are sent to the server independently and within the PostgreSQL server the substitution and escaping is made.  So, there's no way to get this substitution from this library.  There may be query builder libraries in node that do client side substitution, but out of the scope for this package.
