### ISSUE TITLE
array_remove() function not updating array

### ISSUE THREAD

**Issue by MrFridunath** [brianc/node-postgres#2756]
array_remove() function not working in javascript...

I have this function, and the query is executed but the value is not removed. The type of up_voted_posts is VARCHAR[]. The same applies with array_append, I do not know what is it, i execute the same query with pgAdmin4, and i have no problems but with javascript, the array is not updated...

```js
async function updateAccountUpVotePostRemove(username, postUID) {
	const client = new Client(pgCredentials);
	let q;
	try {
		await client.connect();
		q = await client.query("UPDATE accounts SET up_voted_posts = array_remove(up_voted_posts, '" + postUID + "') WHERE username='" + username + "';");
		await client.end();
	} catch (e) {
		console.log(e);
	}
    return q;
}
```

**Comment by charmander** [comment]
- You should use parameterized queries instead of inserting values into SQL by string concatenation.
- If you think this is a bug in pg (it doesn’t look like that’ll be the case), please post a complete self-contained script that reproduces the issue. Otherwise, the pg issue tracker isn’t a good place for questions about how to use PostgreSQL.
