### ISSUE TITLE
parameterized Query for Column is not working as expected 

### ISSUE THREAD

**Issue by matt212** [brianc/node-postgres#2797]
Hi @brianc , 

pg : 8.5.1
node : v16.15.1
machine : windows (WSL ubuntu)

I am facing  issue below 

#### Current scenario ####
```
var baseQuery='select * from employees as a where  $1 >= $2 AND $1 <=$3 limit 10'
var daterange=['a.created_date','1982-07-26 00:00:00','2022-08-25  24:00:00']

client.query(base,columns, function (err, result) {
          console.log(result.rows)
    })

```
the `result.rows` is empty 

#### Expected scenario ####
`result.rows` should return records .
Since when we remove column from parameterized logic  it is returning value from db 
code snippet for non column parameterized
```
var baseQuery='select * from employees as a where  a.created_date >= $1 AND a.created_date <=$2 limit 10'
var daterange=['1982-07-26 00:00:00','2022-08-25  24:00:00']

client.query(base,columns, function (err, result) {
          console.log(result.rows)
    })

```
Any pointers on the same

**Comment by brianc** [comment]
You can't parameterize column names. This is a postgres limitation/decision and nothing we have control over in the driver.  If you need to allow user submitted column names I suggest doing a lookup table in your code where you match user submitted string to a hard-coded set of column names you control because you basically __have__ to use string concatenation in your query:

```js
const allowableColumns = {
  'name': 'name',
  'age': 'age'
}

function doQuery(columnName, value) {
  return pool.query(`select * from users where ${allowableColumns[columnName]} = $1`, [value])
}
```

You can also use [`client.escapeLiteral`](https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/client.js#L447) or `client.escapeIdentifier` for super dynamic queries but I'd only use that if a "white list of allowable literals" doesn't work for your app.

**Comment by Joseph-Pittera** [comment]
With psql version 15.1 it seems to be working now
