### ISSUE TITLE
Stream Duplex: this.stream.setNoDelay is not a function

### ISSUE THREAD

**Issue by mdoliner** [brianc/node-postgres#2896]
My project is trying to set up a SOCKS5 proxy stream using pg 8.x.x. We are using socksjs which creates a Duplex stream to supply to pg. pg is attempting to call `this.stream.setNoDelay` which does not appear to be part of the Duplex interface, causing the above error `this.stream.setNoDelay is not a function`

**Comment by brianc** [comment]
You can either monkey patch whatever you're passing to the connection or submit a PR to check if nodelay is a function before calling it.  Probably _easier_ to just monkey patch the thing you're passing in w/ a `noop` function because a PR requires some tests and so on...but either way should solve your issue!
