### ISSUE TITLE
How to batch multiple statements into one call?

### ISSUE THREAD

**Issue by siddjain** [brianc/node-postgres#2919]
How do I batch multiple statements into one call with this library?

**Comment by brianc** [comment]
If you're using parameters you cannot, by design of the postgres binary protocol. If you have non-parameterized statements you can batch them by separating them w/ semi-colons:

```js
client.query(`
INSERT INTO foo (bar) VALUES ('baz');
INSERT INTO qux(zug) VALUES ('yar');
`)
```

Please note I don't recommend using non-parameterized sql in an environment where you're accepting data from users or untrusted data....the risk of sql injection is not worth the extremely small performance benefits you'll get w/ batching queries.
