### ISSUE TITLE
Posible bug with socket disconnect event when doing a reboot

### ISSUE THREAD

**Issue by Ncifra** [brianc/node-postgres#3003]
We have an AWS Postgres cluster with 2 instances, and we are using `LISTEN`/`NOTIFY` (actually `pg_notify` from the db) notifications. It seems though that when restarting Postgres with RDS, we don't get any event in the `error` callback, nor any of the other ones, `drain`, `end`. Below is a sample of how the client has been initalized:

```
    this.client = new Client({ connectionString });
    this.client.on('error', async error => {
      if (error) {
        throw error;
      }
    });
```
Are we missing anything? If we don't get notified of the server reboot, we are losing notifications, since the new notifications from the server are not being listened to anymore (we would need a new `LISTEN` query), so this behaviour should not be normal.

**Comment by sehrope** [comment]
The TCP keep alive would eventually catch this but by default that's a long time.

To make sure that the connection for listen / notify is still active, you should be periodically running a test query, e.g. `SELECT 1` to ensure the connection is still alive. Give it a short timeout and if it does not complete, consider the connection broken and create a new one.

It may seem a bit low level to have to do this, but it's like that for every driver handling listen / notify as it's always possible for the connection to close. It could be from a server restart, a kill -9, NAT breakage for the socket, or really anything else that terminates the connection in a way that does not cleanly shutdown.

Note that it's impossible to never miss events from LISTEN / NOTIFY. That's true for any non persistent queue. To get around that a common pattern is to INSERT into an event table for each event so the listener can pick up where it left off. Once it's caught up, it can continue with LISTEN / NOTIFY events. To make sure you don't miss anything the order has to be:

1. Create connection
2. LISTEN for events and push them onto a client side queue
3. SELECT for any missing events since the previous last known event and push them on the client side queue
4. Sort / dedupe the client side queue so all the events you know are in order and only appear once
5. Process events in the queue
6. Process any new events in the order they are received

Note that if you do not LISTEN before you query for missing events, you have a race condition and could skip something that happens in between you issuing the LISTEN and the server beginning to send you events.

**Comment by Ncifra** [comment]
> The TCP keep alive would eventually catch this but by default that's a long time.

well this actually went on with no failure for more than 10 days, so I don't think it is expected to be more that much, no?

>Give it a short timeout and if it does not complete, consider the connection broken and create a new one.

What would be a practically safe timeout for that? So I currently have done this:

```
  private setConnectionChecker() {
    this.connectionChecker = setInterval(async () => {
      try {
        await this.client.query('SELECT 1');
      } catch (err) {
        await this.client.connect();
        // resume other actions here like listening again
      }
    }, 1000);
  }
```
This is a method we call when we initialize a sort of Postgres wrapper class. In this case we query every second, which I think is enough and at the same time doesn't spam the server, and we would also maybe reconnect here. But the query timeout I think is set on the client level, and we can't set it specifically for that query, right? In that case setting a short timeout for the `SELECT 1` means setting a short one for all queries.

>Note that it's impossible to never miss events from LISTEN / NOTIFY. That's true for any non persistent queue. To get around that a common pattern is to INSERT into an event table for each event so the listener can pick up where it left off. Once it's caught up, it can continue with LISTEN / NOTIFY events.

Yes we do that already for cases like these where the notifications are missed, but due to not catching this error, we don't know that we need to query for any missed events.

Thanks

**Comment by sehrope** [comment]
> well this actually went on with no failure for more than 10 days, so I don't think it is expected to be more that much, no?

I think you have to explicitly enable keepAlive. It's off by default.

> What would be a practically safe timeout for that?

There's no one answer to this. The shorter the timeout, the more you're bombarding the server and potentially suffering from false positives. The longer the timeout, the longer the period you may be offline. Using something between one and ten seconds is common.

> So I currently have done this: ...

You can't reconnect a dead client. You'd have to scrap the old one and create a new one. But, otherwise yes that's the idea. You should remove all the old listeners, intervals, and timeouts, then create them again on the new connection.

> But the query timeout I think is set on the client level, and we can't set it specifically for that query, right? In that case setting a short timeout for the SELECT 1 means setting a short one for all queries.

You can wrap whatever the invoker of the connection test and listener with Promise.race(...) to have the timeout be directly controlled. That way it gets triggered if any part of the connection test slows down.

**Comment by Ncifra** [comment]
> I think you have to explicitly enable keepAlive. It's off by default.

Thanks for this

>There's no one answer to this. The shorter the timeout, the more you're bombarding the server and potentially suffering from false positives. The longer the timeout, the longer the period you may be offline. Using something between one and ten seconds is common.

Yes confirmed this, tried with 100ms and was getting some weird logs. I think anything above 1000ms should be good.

This is what I came up which actually seems to work okay. People can tweak these values, but I think it's a starting point for anyone wanting to have something to test:

```
  private setConnectionChecker() {
    this.connectionChecker = setInterval(async () => {
      try {
        await Promise.race([
          this.client.query('SELECT 1'),
          new Promise((resolve, reject) => {
            setTimeout(() => {
              return reject(new Error('query_checker_timeout_expired'));
            }, 1000);
          }),
        ]);
      } catch (err) {
        if (this.connectionChecker) {
          clearInterval(this.connectionChecker);
        }
       // handle error, log or whatever
        let retries = 0;
        while (retries < 3) {
          try {
            this.client = new Client({
              connectionString: this.connectionString,
              keepAlive: true,
            });
            await this.client.connect();
            this.event.emit('reconnected');
            break;
          } catch (connectionErr) {
            console.error(connectionErr);
            retries += 1;
            if (retries === 3) {
              throw connectionErr;
            }
          }
        }
        this.setConnectionChecker();
      }
    }, 2000);
  }
```

This is a method in the wrapper class, where I retry up to 3 times to reconnect, after that I just throw the error. The checker query runs every 2 seconds, while the timeout for that is 1 second. I have also added an EventEmitter class which I use to emit and can be used for any other classes that use this wrapper to be notified of the reconnection.

Thanks @sehrope
