### ISSUE TITLE
Problem with table with numeric columns names

### ISSUE THREAD

**Issue by jortilles** [brianc/node-postgres#3068]
I have a table with numeric columns names. I know is not the best but i have it like that....

it would be like this:
create table foo ( col1 varchar(20),  "2015" float,  "2016" float);
insert into foo (  "var", 1.1, 1.3);
insert into foo (  "var2", 1.14 1.43);

if i do this select works fine:
select "2015", col1  from foo  ;

if i do this select  it return the resultset in wrong order:

select col1, "2015" from foo ;

**Comment by charmander** [comment]
Keys that look like array indexes are first in the enumeration order of an object in JavaScript. You generally shouldn’t be relying on the enumeration order of an object anyway in any situation; in this one, you already know the correct order because you’re the one who made the query, so you can just access the results in that order. See also [the `fields` property of the Result object](https://node-postgres.com/apis/result#resultfields-arrayfieldinfo) and [`rowMode: 'array'`](https://node-postgres.com/apis/client#queryconfig).

**Comment by charmander** [comment]
… Or, if you’re referring to the order of rows, there isn’t one either. You always need an `ORDER BY` if you rely on an order.
