### ISSUE TITLE
How to pass array and other values as param in Typescript? 

### ISSUE THREAD

**Issue by raspacee** [brianc/node-postgres#3198]
Passing an array only works fine like below
```
const g = ["e70fb7d1-ebe3-4cb7-a250-359f9646f47b"];
const data = await pool.query('select * from review where author_id = any($1::uuid[]);'), [g] );
```

But passing other values at the same time causes a type error
```
const g = ["e70fb7d1-ebe3-4cb7-a250-359f9646f47b"];
const data = await pool.query('select * from review where author_id = any($1::uuid[]) and age=$2;'), [g, 33] );
```
No overload matches this call. The last overload gave the following error. Argument of type '(number | string[])[]' is not assignable to parameter of type '(err: Error, result: QueryResult<any>) => void'. Type '(number | string[])[]' provides no match for the signature '(err: Error, result: QueryResult<any>): void'.

**Comment by sehrope** [comment]
Check the version of the `@types/pg` that you're using as there was bug recently that I believe was subsequently fixed:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68871#issuecomment-2007778546

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69053

If you happened to get the version in between that might be the issue. If you still have the issue after upgrading to the latest, try *downgrading* to the version before that those changes (just for the types) as perhaps something else is broken.

Either way, it's not an issue with this library as the types are not defined here and any issue would need to be fixed in the DefinitelyTyped repo.

**Comment by raspacee** [comment]
Thanks! upgrading `@types/pg` to 8.11.5 fixed the issue.
