### ISSUE TITLE
Passing in quoted tabled names for a create table query

### ISSUE THREAD

**Issue by DanielCoder834** [brianc/node-postgres#3221]
I want to be able to create a tabled named  "user" so I wrote this piece of code: 
```
const client = await this.pool.connect();
sql= 'CREATE TABLE IF NOT EXISTS "user" (id UUID PRIMARY KEY DEFAULT gen_random_uuid())'; 
await client.query(sql); 
```
When I run the code, I get a parser error. If I run it with user without the quotation marks, I get an error for user is a special name for postgres. I have since found a round about solution to my initial problem which I was trying to use this library to solve. 

Since I ran into this dilemma and I don't want other developers to fall into this pitfall, I think this would be the best place to bring it up. If you can't solve the issue, that's fine, but I thought it would be best for contributors and future developers to know about this issue. :)

**Comment by charmander** [comment]
> When I run the code, I get a parser error.

What is the parser error?

**Comment by DanielCoder834** [comment]
These are the two errors I got: 
<img width="586" alt="Screenshot 2024-05-27 at 12 01 21 PM" src="https://github.com/brianc/node-postgres/assets/55712502/5d7a69a6-5eaf-4e65-a3b3-99d31fcd94ca">
<img width="576" alt="Screenshot 2024-05-27 at 12 01 34 PM" src="https://github.com/brianc/node-postgres/assets/55712502/dff66cc0-00c1-419b-8c0e-46da564e6ae2">

**Comment by charmander** [comment]
Those aren’t parser errors. The important part is “terminating connection due to administrator command”, which is an error sent by the PostgreSQL server that pg is exposing to you. I don’t know why you would get that when running a particular query, but it’s almost certainly not related to pg (coincidental timing? maybe a bad bouncer or WAF[^1] – are you connecting directly to a vanilla PostgreSQL server?); try running the same query with a connection established the same way by a different client (e.g. `psql`), and you’ll probably get the same error. (Or try running it with pg again if you didn’t make sure you could reproduce it the first time around.)

[^1]: web application firewall

**Comment by DanielCoder834** [comment]
Thank you for the help. I will try a different client and see if it gives me a different result
