### ISSUE TITLE
Use array constructor syntax for array serialization

### ISSUE THREAD

**Issue by timvandam** [brianc/node-postgres#3292]
Hi! Would it be possible to change up the array serialization logic?

The current code uses a text array literals like `'{1,2,3}'`. While this generally works, using array constructor syntax like `ARRAY[1,2,3]` would allow postgres to do some more type inference, saving a couple of keystrokes here and there.

One example where this would help is in `UNNEST` statements.
These two examples illustrate why `ARRAY[]` would be nice to have:

```sql

-- works 😎
SELECT *
FROM UNNEST(ARRAY[1,2,3], ARRAY[3,4,5]);

-- fails 😢
-- [42725] ERROR: function pg_catalog.unnest(unknown) is not unique Hint: Could not choose a best candidate function. You might need to add explicit type casts. Position: 15
SELECT *
FROM UNNEST('{1,2,3}', '{3,4,5}');

-- works again 😎
SELECT *
FROM UNNEST('{1,2,3}' :: int[], '{3,4,5}' :: int[]);
```

While typing `:: int[]` every now and then is not a big deal, it is easy to accidentally get the type wrong, so letting postgres figure it out automatically would be great to have when possible.

I am not aware of any disadvantages of `ARRAY[]` over `{}`.

The current serialization logic is situated here:

https://github.com/brianc/node-postgres/blob/54eb0fa216aaccd727765641e7d1cf5da2bc483d/packages/pg/lib/utils.js#L14-L41

**Comment by charmander** [comment]
`ARRAY` is SQL syntax, not a parameter value, so this isn’t possible.

**Comment by charmander** [comment]
But to address your underlying problem instead of the impossible proposed solution: PostgreSQL supports providing type OIDs to go along with parameter values, which pg means to expose as the `types` option but which doesn’t currently work as intended (TODO: issue reference). Providing an array of OIDs manually isn’t much more convenient than SQL casts as-is, but it is a mechanism that libraries using pg could apply automatically based on input types.
