### ISSUE TITLE
Getting connection timeout even after setting connectionTimeoutMillis, and idle_in_transaction_session_timeout

### ISSUE THREAD

**Issue by abhinavvsinhaa** [brianc/node-postgres#3348]
I'm trying to connect with an Amazon Redshift Serverless database using npm pg package, and this is how my code looks like for trying to establish a connection with the database: 
~~~
let config = {
		host,
		port,
		user,
		password,
		database: databaseName,
		connectionTimeoutMillis: 120000,
		idle_in_transaction_session_timeout: 120000,
		ssl: {
			rejectUnauthorized,
		},
	};
	
let pgClient;

const startTime = performance.now();
try {
	pgClient = new pg.Client(config);
	await pgClient.connect();
	return true;
} catch (error) {
	const endTime = performance.now();
	const timeTaken = endTime - startTime;
	if (timeTaken > TIMEOUT_IN_MS) {
		logger.warn(`Redshift connection took more than ${TIMEOUT_IN_MS}ms to complete. Took ${timeTaken}ms`);
	} else {
		logger.info(`Redshift connection took ${timeTaken}ms to complete`);
	}
}
~~~

And this is getting logged `Redshift connection took 75042.1265ms to complete`
I even tried logging the defaults for these values such as `connectionTimeoutMillis`, `idle_in_transaction_session_timeout`, but could not get much information there. 

Can you tell me if there is an upper limit or something like that? Or how can I resolve this issue?

**Comment by charmander** [comment]
The default `connectionTimeoutMillis` is no timeout, so setting it can only add a stricter timeout, never raise an existing timeout. `idle_in_transaction_session_timeout` isn’t relevant here.

You should probably log `error` (or just not catch it) to get some useful information, and the problem is probably not going to be solved by waiting longer than 75 seconds to connect.
