### ISSUE TITLE
Query logging/debug output

### ISSUE THREAD

**Issue by pyoio** [brianc/node-postgres#433]
Hi, I went through the documentation/examples and I can't find any obvious way to enable debug/logging output. 

I'd just like any query being executed to be automatically output to console.log, is this currently possible?

**Comment by kerimdzhanov** [comment]
Hi!

What do you guys think about triggering event like `pg.on('query')` to give ability to bind any kind of logger/debugger?

For example, I have some `lib/db.js` in my project:

```js
var pg = require('pg');
var bunyan = require('bunyan');

pg.on('query', function (sql) {
  bunyan.debug(sql);
  // or simply console.log(sql);
});

// ...
```

**Comment by elfet** [comment]
Is it possible to log queries with exact params?

**Comment by chriszrc** [comment]
I ended up enabling sql logging for the local postgres db directly, and this actually works quite well -

http://stackoverflow.com/a/722236/228369

**Comment by artyomtrityak** [comment]
You can use think monkeypatch snippet to log queries

```js
const oldPoolQuery = pool.query;
  pool.query = (...args) => {
    console.log('QUERY:', args);
    return oldPoolQuery.apply(pool, args);
  };
```

This does not logs final query (that you should use postrgresql logging) but at least you will be able to see function calls. This might be helpful for simple use-cases.

**Comment by tugorez** [comment]
How about this ? using ES6 and replacing and interpolating query values.
```javascript 
const Query = require('pg').Query;
const submit = Query.prototype.submit;
Query.prototype.submit = function() {
  const text = this.text;
  const values = this.values;
  const query = values.reduce((q, v, i) => q.replace(`$${i + 1}`, v), text);
  console.log(query);
  submit.apply(this, arguments);
};
```
This interpolates the query string with actual values.

**Comment by jwhiting** [comment]
@tugorez That's progress, but it still doesn't log valid SQL since it's just doing simple string conversion on the inputs, which is not what happens in actual fact. Case in point: pass a date in as an argument. What you see is the toString() representation of the date which is not valid SQL. The library is doing deeper preparation of the query arguments, and while I haven't looked thoroughly through the code, it appears to be sending the statement template and arguments using the extended query api provided by postgres - https://www.postgresql.org/docs/devel/static/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY - so it may not be possible to actually get the valid final SQL, not sure.

**Comment by retorquere** [comment]
@tugorez when I try that code I get `Cannot read property 'reduce' of undefined` on the line that says `const query = values.reduce((q, v, i) => q.replace(`$${i + 1}`, v), text);`

**Comment by retorquere** [comment]
Ah never mind, it does that when you have a query without parameters. While still not valid SQL, I settled on

```
Query.prototype.submit = function () {
    const text = this.text;
    const values = this.values || [];
    const query = values.reduce((q, v, i) => q.replace(`$${i + 1}`, JSON.stringify(v)), text);
    console.log(query);
    submit.apply(this, arguments);
  };
```

**Comment by mo** [comment]
I'm porting a node+mysql package to node+postgres and for mysql I used mysql.format() to log the final SQL to the console. Since escaping seems to be implemented server side in postgress, any pg.format() function would need to roundtrip to the server making it very inefficient. So I suppose the options are A) using pg-format and hoping that it outputs the same as the server, or B) logging the final query inside the postgres server instead.

**Comment by bf** [comment]
@retorquere your example still works. thank you

**Comment by mariusa** [comment]
How could this be adapted for `pg-cursor` ?

**Comment by hos** [comment]
With this, you can only log queries where you add comment `--debug`.

```sql
const submit = Query.prototype.submit

Query.prototype.submit = function patchedSubmit() {
  const text = this.text
  const values = this.values || []
  const query = text.replace(/\$([0-9]+)/g, (m, v) => {
    const value = values[parseInt(v, 10) - 1]
    if (typeof value === 'string') return `'${value}'`
    if (value instanceof Date) return `'${value.toISOString()}'::timestamptz`
    if (value instanceof Number) return value.toString()
    return JSON.stringify(values[parseInt(v, 10) - 1])
  })

  if (/--debug/i.test(query)) {
    logger.log(query)
  }

  // eslint-disable-next-line prefer-rest-params
  submit.apply(this, arguments)
}
```

**Comment by egorovli** [comment]
> How could this be adapted for `pg-cursor` ?

You could do exactly the same with `Cursor`:

```typescript
let submit = {
  cursor: Cursor.prototype.submit
}

Cursor.prototype.submit = function patchedSubmit() {
  let text = this.text
  let values = this.values || []
  let query = prettyPrintQuery(text, values)

  if (/--debug/i.test(query)) {
    console.log(query)
  }

  submit.cursor.apply(this, arguments)
}
```
