### ISSUE TITLE
Option to convert query rows snake_case fields to camelCase

### ISSUE THREAD

**Issue by rynz** [brianc/node-postgres#502]
Is it possible for `node-postgres` to have a configuration option to convert snake_case database fields into camelCase automagically for the `result.rows` when a successful query is returned?

I understand I could write a function to loop and pass it through myself, but I feel like that would be a double-up / extra process work. As the query already builds the rows, why not have the option of camelCase conversion too rather than query building the rows, then having to re-build them myself.

**Comment by jtlapp** [comment]
@hoegaarden's "pg-camelcase" solution shows why node-postgres should provide an official hook: it intercepts the node-postgres internal method `handleRowDescription`, making it efficient but fragile. It's not good for one library to depend on the internals of another if the same party isn't responsible for both.

I want my client's solution to last as long as possible, and I don't want to riddle my queries with 'AS' clauses, so I'm using the following TypeScript function when I need to pass a row to something that requires camelcase:

```ts
/**
 * Converts a query result row from snakecase column names to camelcase.
 */
export function toCamelRow<T>(snakeRow: Record<string, any>): T {
  const camelRow: Record<string, any> = {};
  for (const [snakeColumn, columnValue] of Object.entries(snakeRow)) {
    let camelColumn = snakeToCamelMap[snakeColumn];
    if (camelColumn === undefined) {
      const words = snakeColumn.split('_');
      camelColumn =
        words[0] +
        words
          .slice(1)
          .map((word) =>
            word == 'id' ? 'ID' : word[0].toUpperCase() + word.substring(1)
          )
          .join('');
      snakeToCamelMap[snakeColumn] = camelColumn;
    }
    camelRow[camelColumn] = columnValue;
  }
  return camelRow as T;
}
const snakeToCamelMap: Record<string, string> = {};
```

It reflects my preference for capitalizing `ID` so that I read it as the letters I and D and not as 'id', the counterpart of 'ego'.

**Comment by malthe** [comment]
I agree with @brianc that the driver should not have this sort of cleverness built-in, but it's nice to have an official hook that makes it simple.

In [ts-postgres](https://www.npmjs.com/package/ts-postgres), there's a `transform?: (name: string) => string` [configuration option](https://malthe.github.io/ts-postgres/interfaces/Query.html) which allows you to plug in a function such as `snakeToCamelMap`. It's naturally called exactly once per column no matter the number of rows retrieved.
