### ISSUE TITLE
"sorry, too many clients already" is handled as a permanent error

### ISSUE THREAD

**Issue by rngadam** [brianc/node-postgres#557]
Suppose I have the default max_connections for postgres set to a value lower than the pool size pg.defaults.poolSize (which, as I understand it, is hardcoded into defaults.js and not changeable programmatically except by changing the pg source code?):

```
$POSTGRESBINDIR/postgres -c max_connections=3
```

This means that after 3 connections, the pool will crash and burn with:

```
     Error: error fetching client from pool error: sorry, too many clients already
    at /home/rngadam/letsface/src/pgspjs/sp.js:282:25
    at pools.getOrCreate.pool.connect (/home/rngadam/letsface/src/node-postgres/lib/pool.js:75:25)
```

However, if it did wait for another connection to be released, this should still work as the other three clients are still valid and coming in and out the pool.

Should the handling of this particular error be different? The pool treat it as if the pool size was in actually smaller.

The fix right now is to always make sure the pool is smaller than max_connections.

**Comment by agmoyano** [comment]
Hi @brianc, first of all, thank's for this awesome library!!

I know this issue closed in 2014, but I must agree with @rngadam in this point.. I've got a postgresql with max_connections set to 100, and still get this error sometimes.. I've got a 3rd party app (beyond my control) that opens several connections per web page visited. 

The number of connections available to my postgres in a given time cannot be determined.

In the app I'm developing, max connections is set to 5 (way below what postgres max_connections is set to), and sometimes fails when tries to connect the 4th client.

It would be nice, if you've got already clients in the pool, and this error shows up, to automatically wait for a client to be released, instead of crushing.

Thanks

**Comment by charmander** [comment]
> I've got a 3rd party app (beyond my control) that opens several connections per web page visited.

@agmoyano You could put [PgBouncer][] between it and your database.

[PgBouncer]: https://wiki.postgresql.org/wiki/PgBouncer

**Comment by Kartik-Jagtap** [comment]
I have set max_connection to 900, i am using Springboot microservices, still geting "too many client issue". Please help.

**Comment by charmander** [comment]
@Kartik-Jagtap Are you sure that’s related to pg/node-postgres (Node.js)?
