### ISSUE TITLE
node-postgres not being able to handle large inserts?

### ISSUE THREAD

**Issue by sidazhang** [brianc/node-postgres#581]
I am getting this error while executing a large transaction. 

``` bash
{ 
[error: bind message supplies 14472 parameters, but prepared statement "" requires 80008] 
}
```
1. I am inserting 10001 rows and each row has 8 columns.
2. I can confirm that I did supply all 80008 parameters but for some reason, I keep getting this bind message supplies 14472 parameters error
3. My work_mem is 1mb and maintenance_work_mem is 16mb

My resolution:
I had to write the sql query into a file ('insert.sql') and then I went into postgres console and did `\i insert.sql` and then it was fine.

Note: With node-postgres, I use node-sql to generate prepared statements, however, when I did `\i insert.sql` I produced a raw sql statement.

Some guesses:
Idea 1: Maybe because I am inserting so many rows at once that postgres dies after processing 14472 parameters?

I have had similar problems with node-postgres in the past where when I used node-postgres to do large inserts, it seemed not to be able to handle it well. And with large inserts I always resort back to `\i insert.sql`

**Comment by skilbjo** [comment]
@sidazhang could you provide an example of your bulk insert code?

**Comment by spion** [comment]
This is a problem with node-buffer-writer, fixed here: https://github.com/brianc/node-buffer-writer/pull/3

**Comment by kibertoad** [comment]
@brianc This issue is 100% reproduceable on 8.5.1 when doing an insert like this:
```
insert into "merge_table" ("id", "value") values ($1, $2), ($3, $4), ($5, $6), ($7, $8), ($9, $10), ($11, $12), ($13, $14), ($15, $16), ($17, $18), ($19, $20), ($21, $22), ($23, $24) <...>on conflict ("id") do update set "id" = excluded."id", "value" = excluded."value"
```
with values passed being `[0,0,1,1,2,2<...>]`.

This happens when trying to insert 32768+ rows. It works with 32767 rows (65534 params), so it really looks like it is an issue related to 32-bit hard cap on params somewhere. That would explain the exact error that original reporter was getting - `80008 expected, only 14472 supplied` looks like an overflow after 32-bit integer (max 65536) is full.

**Comment by brianc** [comment]
The 16-bit hard cap on params is specified as part of the postgres protocol and is a constraint within postgres itself.  Here's the code [that writes the count of params](https://github.com/brianc/node-postgres/blob/master/packages/pg-protocol/src/serializer.ts#L155).  This library could probably throw a friendlier error rather than just having the query crash with a param count mis-match....but it's nothing that we can actually "fix" on our side.

**Comment by kibertoad** [comment]
@brianc Having an informative error message definitely would be great, since people keep hitting this particular scenario. Is it possible to do such check in a non-expensive way?

**Comment by brianc** [comment]
Yeah I think it should be super cheap, can just do

```js
if (params.length > 65535) {
  throw new Error('Postgres only supports up to 65535 parameters in a prepared statement')
}
```
