### ISSUE TITLE
support password-less peer authentication

### ISSUE THREAD

**Issue by andrewrk** [brianc/node-postgres#613]

**Comment by brianc** [comment]
I didn't know `/var/run/postgresql` was the default thing to attempt to connect to if there was no host available in $PGHOST or the connection string. We could change it to fall more in line with other clients.

**Comment by mpekar** [comment]
Doing the following allowed me to connect with ident auth in Debian:

> var pg = require('pg').native;
> pg.defaults.password = "";
> pg.defaults.host = "/var/run/postgresql";
> var pgUrl = "postgres://PG_USERNAME@/DATABASE";

With pg_ident.conf as follows:

> # MAPNAME       SYSTEM-USERNAME         PG-USERNAME
> MAPNAME SYSTEM_USERNAME PG_USERNAME

And pg_hba.conf:

> # TYPE  DATABASE    USER        CIDR-ADDRESS          METHOD
> local   SYSTEM_USERNAME          PG_USERNAME         ident map=MAPNAME

**Comment by btbonval** [comment]
Following the above comment, I was able to get it work using peer auth by changing `pg.defaults.host = '/var/run/postgresql'`. I didn't have to change anything else, and suddenly it works.

I think the problem is the host variable.

The following URIs are documented to work (31.1.1.2 Connection URIs in http://www.postgresql.org/docs/9.4/static/libpq-connect.html):
```
postgresql:///dbname?host=/var/lib/postgresql
postgresql://%2Fvar%2Flib%2Fpostgresql/dbname
```

Of course, replace `/var/lib/postgresql` with the correct file for your system, e.g. `/var/run/postgresql` in my case.

So here's the thing: `'postgres:///?host=/var/run/postgresql'` will work fine for more only if I set `pg.defaults.host = '/var/run/postgresql'`. Shouldn't those URIs be _specifying_ the host parameter so the default is not actually used? I think there is a bug somewhere in the URI processor.

**Comment by art-solopov** [comment]
+1. Spent some time today debugging the weird authentication error.

**Comment by es6Test** [comment]
What is the best way to create a secure user/password system with node + postgresql + your library? Any example out there?

**Comment by bikeshedder** [comment]
Leaving out the hostname should result in a unix domain socket connection rather than using `"localhost"`. That's the way `libpq` works and most (all?) other libraries connecting to postgresql do it as well.

+1 for `postgresql:///dbname`

https://www.postgresql.org/docs/9.5/static/libpq-connect.html#LIBPQ-CONNSTRING

If there is no "correct" way to find the proper path to the socket directory I'd propose to try `/tmp` first which is the default set by PostgreSQL and then `/var/run/postgresql` which is the directory Debian and Ubuntu use. (Fun fact: on my Fedora 25 box I actually have both `/tmp/.s.PGSQL.5432` and `/var/run/postgresql/.s.PGSQL.5432`)

**Comment by charmander** [comment]
@bikeshedder pg doesn’t use connection strings anymore. It’s a supported option:

```javascript
const pool = new pg.Pool({
    host: '/var/run/postgresql',
});
```

**Comment by bikeshedder** [comment]
@charmander having to specify the path to the socket file is rather unintuitive. `libpq` defaults to unix domain sockets and so should any third party connector, no?

How about making "host: null" use the local unix domain socket instead of "localhost"?

**Comment by Aysnine** [comment]
The `host: localhost` can't work, user ident error.
But `host: /var/run/postgresql` is fine.
On my CentOS 7, PostgreSQL 9.6.

**Comment by charmander** [comment]
@Aysnine That’s expected, and you should see the same behaviour with any client; peer authentication only works with local (not TCP) connections.

**Comment by charmander** [comment]
So, peer authentication is supported; we can open a new issue to suggest changing the default to match libpq’s in a future major release.

**Comment by ryanb** [comment]
I ran into this and ended up setting `PGHOST='/var/run/postgresql'` env variable so it does a peer connection to the socket instead of through localhost (as long as you don't pass a host to the connection URI). You may need to set it to `/tmp` or wherever the socket is.
