### ISSUE TITLE
Pg specific Error class for differentiating various errors

### ISSUE THREAD

**Issue by moll** [brianc/node-postgres#700]
Hello,

There are a lot of errors flying around in JavaScript and they all inherit from `Error`. It makes a little difficult to programmatically differentiate between bugs, exceptional cases and regular data validation errors.

I propose node-postgres have a specific error class at least for error and notice responses from PostgreSQL. That would make it easier, for example, to spot and parse constraint errors from connectivity errors and actual bugs. One could use a simple `instanceof` check (or something like `err.name == "PgQueryError"`) rather than duck typing and assuming an error with a `internalQuery` really is one from node-postgres.

**Comment by rpedela** [comment]
Being able to do ```if err instanceof PgError```, or something similar, is quite useful for certain use cases. One such use case, which I happen to have, is when you want to centralize error handling.

My application's backend may call Elasticsearch, Postgres, Stripe, and a few other services. They all have their own way of error handling. They usually adhere to the first parameter in the callback convention, but the error object is a bit different for each service. And in the case of Elasticsearch, the official Node module only returns client-specific errors in the Error object. Errors from the server are found in the response. I want the application's backend to return a unified Error object so that the web front-end, API, etc can easily return a sensible error to the user.

There are several ways to do this, but I prefer a centralized error handling function. Something like ```if (err) { handleError(err) }```. Being able to easily differentiate between which service the error came from is important in a centralized function. I prefer this way because I think maintenance is easier. If a new feature is added to the backend, minimal or no changes are needed for error handling. I am not trying to convince anyone this way is the best or right since I think it always depends on the specifics of the use case.

All I am saying is that this is one, reasonable way to perform error handling and if this module can make it easier without hurting existing code and other use cases then why not? Wrapping an error object in a ```PgError``` class helps the centralized error handling case and, as far as I can see, does not hurt existing code or other methods of error handling.

**Comment by moll** [comment]
@rpedela: If you want this now, see [PgError.js](https://github.com/moll/node-pg-error) as I mentioned above. ;)

**Comment by nathanboktae** [comment]
> If you want this now, see PgError.js as I mentioned above. ;)

Except you licensed it as AGPL, so you just wasted your time due to that viral license.

**Comment by moll** [comment]
> Except you licensed it as AGPL, so you just wasted your time due to that viral license.

Umm, PgError.js is **L**AGPL as in Lesser AGPL. That doesn't preclude use in closed source. There are 4 bullet points in the README to make it clear what you can and can't do. ;-)
