### ISSUE TITLE
Plans to suport JSONB insert?

### ISSUE THREAD

**Issue by tagorecaue** [brianc/node-postgres#705]
Do you have plans to allow insertion in new JSONB format without have to convert JSON to String?

I'm trying to read some docs from MongoDb and insert into PostgreSQL 9.4 using stream but I receive this message:

PostgreSQL TypeError: Invalid non-string/buffer chunk

To solve this problem I had to convert JSON to string.

**Comment by rpedela** [comment]
PG's wire protocol supports text and binary modes. I believe ```node-postgres``` only supports both but only text mode is well tested. For text mode, you need to convert the JSON to a string. Even in binary mode, the JSON bytes need to be converted to PG's format. Since you mentined MongoDB, I just wanted to mention that ```BSON != JSONB```.

**Comment by pdiniz13** [comment]
@tagorecaue a simple JSON.stringify should do the trick. Postgres will convert stringified json to jsonb.

**Comment by charmander** [comment]
This seems to have been already supported at the time (except for arrays)… is it still reproducible?
