### ISSUE TITLE
Client#query returns an empty result set when no callback is provided

### ISSUE THREAD

**Issue by bnguyen-atlassian** [brianc/node-postgres#720]
If you execute query without including a callback, the result set provided via the listeners are empty.

I verified this on pg 4.1.1, with the code below.
```
var pg = require('pg');

var config = {
    host: "localhost",
    port: 5432,
    database: "test",
    user: "test"
};

pg.connect(config, function (err, client, done) {
	var query = client.query('SELECT 1');

	query.on('end', function(result) {
		console.log(result);
		done();
		client.end();
	});
});
```

Which results in:
```
$ node test
{ command: 'SELECT',
  rowCount: 1,
  oid: NaN,
  rows: [],
  fields:
   [ { name: '?column?',
       tableID: 0,
       columnID: 0,
       dataTypeID: 23,
       dataTypeSize: 4,
       dataTypeModifier: -1,
       format: 'text' } ],
  _parsers: [ [Function] ],
  RowCtor: [Function],
  rowAsArray: false,
  _getTypeParser: [Function] }
```

**Comment by brianc** [comment]
This is expected behavior. Rows are not buffered & stored in an array if you don't supply a callback. This is to prevent exploding your memory space for larger results-sets as you are expected to handled each row as it comes in on the `query.on('row', ...)` event listener.  There's a bit of documentation around it here: https://github.com/brianc/node-postgres/wiki/Client#method-query-simple
