### ISSUE TITLE
Strange connections closing behaviour

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#740]
This is following my work on pg-promise, which I just started: https://www.npmjs.com/package/pg-promise, to offer a better union between PG and Promise than the ones available.

ISSUE:

Impossible to fathom the behaviour of the library when releasing or closing connections. See the following simple code snippet:

```
    pg.connect(config, function (err, client, done) {
        if (!err) {
            done();
            client.end();
        }
    });
```
- If we do not call client.end(), then the node process waits for about 30 seconds before it terminates, while the  library has no recommendations for when such call should be made.
- If we just remove done() then the process terminates immediately just as client.end() is called, but this goes against recommendations in the library's documentation;
- If we call both done() and client.end() exactly as in the example above, it suddenly takes about 2-3 seconds for the node process to terminate after client.end() is called.

And while I'm trying to implement my own library to address the issue of automatic connection release, I cannot come to an understanding of how this should be handled properly in different scenarios.

Please help sort this out.

Library used: 4.3.0, NodeJS 0.10.36

**Comment by VitalyTomilov** [comment]
If you find the endeavor with pg-promise interesting, I appreciate if you could list it on your page along with the other libraries that extend PG.

**Comment by brianc** [comment]
If you want to close the connection in the event of an error or for any reason pass the `error` object (or anything truthy) to the `done` callback.  This will cause the pool to close the client. Do _not_ do this on every single query or you're effectively never pooling connections.

You _must_ call `done` when you want to release the client back to the pool.  If you don't call this then you will end up checking out all available clients in the pool.  Whether or not you pass `truthy` value to the `done` call to destroy the client after returning it to the pool is up to you.

Waiting for 30 seconds to close the app because the pool has a 30 second time out is something you have to account for specifically.  You need to call `pg.end()` when you're ready to shut down your application - so handling shutdown is a specific case you have to account for.

Using the connection pool is entirely optional. If you need different pooling behavior you can create clients yourself with `new pg.Client()` and handle pooling with any approach you think is best.

**Comment by VitalyTomilov** [comment]
@brianc 

In my library (pg-promise) I execute a query and call done() immediately, because at this point the connection is no longer needed. The only exception is within transaction where I call done() after the query is finished. And I never pass anything to method done(), didn't even know that I could.

It when an error occurs, I call done() only when it is not a connect error.

Is this not the correct approach for working with the connection pool?

And again, from your post I still don't understand whether I should ever call client.end() at all.

**Comment by VitalyTomilov** [comment]
I have finished adding the package to GitHub: https://github.com/VitalyTomilov/pg-promise

And appreciate if you could, please list it in chapter Extras of your PG project.

**Comment by vitaly-t** [comment]
No longer needed.
