### ISSUE TITLE
Query's "on row" function signature should be flipped

### ISSUE THREAD

**Issue by ross-nordstrom** [brianc/node-postgres#754]
Here's what the current `on('row')` function signature looks like:

```js
var query = client.query('SELECT name, age as user_age FROM users');
    query.on('row', function(row, result) {
      result.addRow(row);
    });
```

If it were flipped to be `function(result, row)`, it would behave just like a normal reducer function, making the usage of this library a bit more natural.

Thoughts? Is there a particular reason the arguments are ordered as is?

**Edit:** An additional extension would be to take a seed value for `result` and fully embrace the reduce :)

**Edit 2:** It might help if I share why I care about this -- basically to reformat the response structure. The default response structure is a very large structure, and in some cases I'd like to alter it to a slimmer structure while data is streaming in so as to minimize my memory footprint.

Here is an example response from this client followed by 2 alternative representations of it (simply reformatted):

**Default format:** The fact that the column names are repeated for every single row can be inefficient memory-wise.
```js
{
  rows: [
    {
      colA: a1,
      colB: b1,
      ...,
      colZ: z1
      },
    {
      colA: a2,
      colB: b2,
      ...,
      colZ: z2
      },
      ...
  ],
  rowCount: ...,
  ...
}
```

**Alternative 1 - "Tabular format":** This resembles how CLI tools like `psql` might print the data, and how you might structure data in preparation for rendering a (HTML) table in a UI
```js
{
  columns: [ 'colA', 'colB', ..., 'colZ' ],
  rows: [
    [ a1, b1, ..., z1 ],
    [ a2, b2, ..., z2 ],
    ...,
    [ aN, bN, ..., zN ]
  ],
  rowCount: ...,
  ...
}
```

**Alternative 2 - "Indexed format":** This is a similar representation to the default, but saves a lot of space by not duplicating the column names
```js
{
  rows: {
    colA: [ a1, a2, ..., aN ],
    colB: [ b1, b2, ..., bN ],
    ...,
    colZ: [ z1, z2, ..., zN ]
  },
  rowCount: ...,
  ...
}
```

**Comment by brianc** [comment]
You can use `rowMode: 'array'` as a config option to your queries to have them return rows as an array without column names instead of values.  [here are some example tests](https://github.com/brianc/node-postgres/blob/ac0d1c71c2a29fff42aac42d70e87d95ba1b595f/test/integration/client/results-as-array-tests.js)

I don't think you'd actually see much improvement on memory usage since the way v8 handles the result objects is with an assembly backed structure, not an in-memory `Hashmap<String, String>` or anything like that.

The `row` event emits a row object (or array) as its first parameter because that was the original signature of the event handler.  To maintain backwards compatibility when I added the `result` to the row event emitter I didn't switch the order of the arguments.  I also think it makes sense to have the event emit the object its describing as its first parameter, and the results object 2nd since it's less likely to be accessed and is less semantic to flip them. 

It's been >4 years with the arguments in that order, I don't think flipping them to make them in a friendlier order to a reducer function is a compelling enough reason to break a substantial amount of backwards compatibility.  You could pretty easily attach a reducer _like_ function to the `row` event and handle reduction/collection in that way.  I also suggest if you're getting fancy with large query results and care about keeping memory footprint low you look at [pg-query-stream](https://github.com/brianc/node-pg-query-stream) for a node-like way of solving this kinda thing.

**Comment by ross-nordstrom** [comment]
Thanks for the feedback! I'll take a look at pg-query-stream, and it's admittedly easy to wrap the `row` event with a closure to easily achieve what I want.
