### ISSUE TITLE
Support for multiple result objects

### ISSUE THREAD

**Issue by irakliy81** [brianc/node-postgres#757]
It would be really nice if after sending a single SQL request with 2 or more SQL statements separated by semi-colons, the query callback contained an array of result objects rather than a single object. Currently, something like this returns in a single result object with rows from both SQL statements present in result.rows

```
SELECT * FROM users WHERE id = 1;
SELECT * FROM conversations WHERE user_id = 1;
```

Thanks!

**Comment by vitaly-t** [comment]
PG library always deals with one query at a time. What you are asking for is only possible through a [promise-wrapped transaction](https://github.com/vitaly-t/pg-promise#transactions).

**Comment by irakliy81** [comment]
Thank you for the reply, Vitaly. What I meant was a bit different - rather than sending two separate requests, I am sending a single request with two statements separated by commas (this is already working). In my benchmarking, a single request with two semicolon-seprated statements completes 2x faster than two separate requests.

The only issue I have is parsing the results. Right now, there is a single result object - and when I make a request with two semicolon-separated statements, this single result object contains rows from both requests mixed together. I can parse through them to figure out which row belongs to which statement, but it would be much cleaner if this was already handled by the library (especially since the library maintains correct column names for each row already).

**Comment by vitaly-t** [comment]
@irakliy81, This is not a standard way to do this. If you need to execute more than query at a time, you should use transactions, because this is exactly what they are for. And a transaction will execute at the same speed, and return you properly formatted results from two queries, not mixed ones.

Here's an example with the same library:

```javascript
db.tx(function (ctx) {
    return promise.all([
        ctx.query("SELECT * FROM users WHERE id = 1"),
        ctx.query("SELECT * FROM conversations WHERE user_id = 1")
    ]);
})
    .then(function (data) {
        console.log(data[0]); // print result from the first query;
        console.log(data[1]); // print result from the second query;
    }, function (reason) {
        console.log(reason); // print why failed;
    });
```

**Comment by irakliy81** [comment]
I see. So two SELECT queries executed in a single transaction should run as fast as a single query with 2 semicolon-separated statements? I'll try to test that, and if so - i think the approach that you have will work very well. Thank you!

**Comment by vitaly-t** [comment]
@irakliy81 
Have you made any progress on this?

**Comment by irakliy81** [comment]
@vitaly-t - i haven't had a chance to get to this yet. one of the complications is that my application is written in typescript and there doesn't seem to be typescript definition files available for pg-promise library.

**Comment by sasha-alias** [comment]
You can use node-libpq directly so you are not limited by node-postgres wrapping functionality.
When you pass a query containing two statements to postgresql it parses them, executes and returns both result sets (ofс only if you use async libpq api). So it's just a matter of taking datasets out of postgres and representing in a form you need.
Here is an example which does exactly what you need https://github.com/sasha-alias/pgtabs/blob/master/src/PqClient.js

**Comment by brianc** [comment]
I agree node-postgres should return result as an array if more than one
result set is returned. It will require a backwards incompatible api break
but i think it makes semantically more sense.  Ill happily accept a pull
request with this functionaly, otherwise ill add it to my long list of
things to do. :)

**Comment by irakliy81** [comment]
I would gladly do it but unfortunately I'm very new to node.js and JavaScript in general. So, I don't feel qualified to make such changes yet.

**Comment by irakliy81** [comment]
I thought of a potential way to make this feature a non-breaking change. I wonder if it would be possible to add a "multiResult" property to the defaults. By default, this would be false and in this case, the library would behave as it does now.

However, if multiResult = true, then the callback in client.query() method would always receive an array of result objects, and if there is only one result, only the first element in the array would be populated.

**Comment by brianc** [comment]
I've added a proper fix to this to the `pg@7.0` milestone. Should be out within the month. Sorry for the long delay!!

**Comment by irakliy81** [comment]
Awesome! Thanks!

**Comment by waynebloss** [comment]
Can someone tell me how this works on the network/PostgreSQL side of things? I was under the impression that PG does not support returning multiple resultsets from a query unless they both return the same set of columns.

Does node-postgres send a separate query to PG for each select statement?

I have a ton of stored procedures in SQL Server that do things like `SELECT a, b, c FROM ParentTable; SELECT x, y, z FROM ChildTable; etc...` and when I call that procedure, one network request goes out to the SQL Server and then it returns an array of resultsets, each resultset being an array of rows... I'd like to do something similar with PG if I can.

**Comment by charmander** [comment]
> Does node-postgres send a separate query to PG for each select statement?

@waynebloss No. Postgres sends back a separate set of messages for each SELECT.

**Comment by waynebloss** [comment]
@charmander Thank you!

At first glance this seemed to contradict material that I've found which says that you need to use `UNION ALL` or `refcursor` to get the results of 2 select statements, or send each statement separately [1, 2]. However, I think that I understand what is going on now.

When you send multiple statements separated by a semi-colon, node-postgres will change to `rowMode: 'array'`. This mode does not provide field names and in fact those field names cannot even be accessed since PG only sends metadata for the last `SELECT` statement, as stated here [3].

1. https://stackoverflow.com/questions/11828772/postgresql-combine-multiple-select-statements
2. https://www.google.com/search?q=postgres+multiple+select+resultsets
3. https://www.commandprompt.com/blog/returning_multiple_results_without_a_round_trip/

> This will avoid the round trip. However there is a limitation. If these were tables, the server would only send the metadata of the last SELECT. The metadata being things such as table description, and number of rows returned. So if you return data from 4 tables, you are only going to know what to do with the last of the tables returned.
> 
> So it appears that the wire protocol does indeed support the ability to send multiple sets back but the server / libpq does not support sending multiple sets with isolated metadata.

but then in the comments...

> psql splits that line at the semicolons and sends four distinct commands in four protocol exchanges.

Which is true. However, I believe the information about the wire data to still be correct. So without digging into the code to confirm this, I'm assuming that `node-postgres` is taking advantage of this fact.

**Comment by waynebloss** [comment]
Yeah because after I tried it out, I could see that I am getting field names for all of the resultsets.

This is great!

I just really wish I could find some PostgreSQL documentation that supports this or else I'm going to have to dig into the code to see how it's working myself or find a way to profile PG queries and match them up with network trips. I just want to confirm beyond a shadow of a doubt that there is only one round-trip.

**Comment by charmander** [comment]
@waynebloss node-postgres doesn’t parse queries at all, so if only the query text is changing, the number of messages won’t. That’s the best simple evidence I can come up with.

**Comment by waynebloss** [comment]
@charmander That's a good point.

I hadn't looked at the code yet, I probably should have because it's pretty straightforward. I can see the implementation [here](https://github.com/brianc/node-postgres/blame/94d38f941e9039a2b09a560bdd1410676920edbd/lib/query.js#L61) which simply checks what's coming back from the server to create the array of results. [The commit](https://github.com/brianc/node-postgres/commit/28b330c88ebac2ea3ad565f8f2ce4ebe5c9a5579) that added support for this was tiny.

Thanks for your help all.
