### ISSUE TITLE
Supporting failover

### ISSUE THREAD

**Issue by rngadam** [brianc/node-postgres#760]
If we have a master and two slaves on two machines, I'm unclear as to how pg handles the master going down. There doesn't seem to be a retry while we wait for one of the slave to become master and perhaps get the hostname pointing to its IP to serve requests? 

I'm imagining:

* queue and run queries
 * run query
 * try/catch query to detect connection failure
* on failure
 * keep retrying to connect every x seconds 
  * lookup hostname -> IP
  * connect to possibly updated IP
 * resume queries once the connection is updated

Should this be supported in the application or something to be supported in node-postgres?

**Comment by brianc** [comment]
A good rule of thumb is to check if `libpq` provides the behavior or the postgres client/server protocol has support for it internally.  If those things have that behavior or support it is worth a discussion about adding it to `node-postgres`...otherwise its something that should live in your application code, or even better, a separate module you open-source and provide back to the community with the behavior!  If you are trying to do something and cannot do it because `node-postgres` doesn't have support for something that's also a place we could look at extending things here.  Otherwise, I'm trying to keep new features out of node-postgres itself and encourage them being pushed into add-on or additional modules. :smile:
