### ISSUE TITLE
Inconsistent error reporting

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#791]
Trying to connect to the wrong server name, I'm getting the following error:

* NodeJS 0.12.4: **getaddrinfo ENOTFOUND serverName**
* NodeJS 0.10.38: **getaddrinfo ENOTFOUND**
* IO.js 2.0.2: **getaddrinfo ENOTFOUND serverName serverName:5432**

Why suddenly the very same error is different on all major platforms?

I was trying to write a test for invalid server connections, and was surprised by such inconsistency.

**Comment by brianc** [comment]
That's a node.js issue.  I just propagate the socket error received on a bad connection attempt back up through the client instance to the user.  I assume `error.code` is the same on on platforms - perhaps test against that rather than the entire `error.message` which is likely to change between major and minor versions.
