### ISSUE TITLE
Numeric data type is returned as String

### ISSUE THREAD

**Issue by petersirka** [brianc/node-postgres#811]
Hi,
firstly thanks for this module, it's really great. I have found a problem in `numeric` data type. It's parsed as String.

Maybe I did something wrong or I have used bad DB type.
Thanks for any advice.

**Comment by bendrucker** [comment]
This actually does depend on your column type (http://www.postgresql.org/docs/9.4/static/datatype-numeric.html)

The type parsing here is handled by https://github.com/brianc/node-pg-types

If you dig into the readme, you'll see an example about int8 (64 bit). Those can't be parsed using `parseInt` because JS doesn't support 64 bit ints. 

If you use a specific int type (smallint / 2 bytes, integer / 4 bytes) you'll get the `Number` you're expecting. But because numeric can be way larger than [`Number.MAX_SAFE_INTEGER`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER), the only safe way to parse it is to return a string with full precision. 

The good news is that if you know your numerics are within JS's range, you can override the parser as instructed over at pg-types. Or, even better, you can use a more restrictive column type and it'll happen automatically.

**Comment by petersirka** [comment]
@bendrucker thanks.

**Comment by super-cache-money** [comment]
@bendrucker 

>The good news is that if you know your numerics are within JS's range, you can override the parser as instructed over at pg-types

Any idea/pointer about how to tell whether my numerics are in this range? I'm storing currencies, up to 100 mill ( 100000000.00 ).

**Comment by super-cache-money** [comment]
It seems like they'll always be under the js maxint:

9007199254740992 is 16 numbers long and I only need 10^10 precision (10^8 + 2 for the decimal points - correct?).

**Comment by illz** [comment]
Numeric type is oid 1700, so you can add this in your app.js or similar:
`var types = require('pg').types
types.setTypeParser(1700, function(val) {
    return parseFloat(val);
});
`

**Comment by vzaytsev** [comment]
> var types = require('pg').types
> types.setTypeParser(1700, function(val) {
>     return parseFloat(val);
> });

better use enum

`types.setTypeParser(types.NUMERIC, (value) => parseFloat(value));`

**Comment by vzaytsev** [comment]
> better use enum
> 
> `types.setTypeParser(types.NUMERIC, (value) => parseFloat(value));`

 TypeId was moved to  types.builtins

types.setTypeParser(types.builtins.NUMERIC, value => parseFloat(value))

**Comment by illz** [comment]
> > better use enum
> > `types.setTypeParser(types.NUMERIC, (value) => parseFloat(value));`
> 
> TypeId was moved to types.builtins
> 
> types.setTypeParser(types.builtins.NUMERIC, value => parseFloat(value))

You could just circle back to my original solution, use the ID 1700, and you wouldn't ever have to update

**Comment by Taycode** [comment]
So I am trying to understand something. I am trying to build a wallet system where the balance is a numeric data type.

From the issues I have read on this, ParseInt might cause data loss and precision loss. So how can I do an addition or reduction to the balance ?

I can't find an increment or decrement on drizzle either.

**Comment by hawaiikaos** [comment]
For anyone using typescript:

```
import pg from 'pg';
var types = pg.types;
types.setTypeParser(types.builtins.NUMERIC, (value: any) => parseFloat(value));
```

**Comment by boromisp** [comment]
If you don't want to lose precision, you will have to use something like this instead of the native `Number` type:
https://github.com/MikeMcl/big.js
https://github.com/MikeMcl/decimal.js
https://github.com/MikeMcl/bignumber.js

**Comment by jazoom** [comment]
As of Drizzle 0.41.0 there is now `mode: "number"`.

`price: numeric("price", { precision: 12, scale: 2, mode: "number"})`
