### ISSUE TITLE
client.query row events vs end event

### ISSUE THREAD

**Issue by epikhighs** [brianc/node-postgres#814]
This is a usage question.

When querying for a large number of rows.  Is it better to do a transformation step during each row event or at the end of the query in the 'end' event?  The transformation is a renaming of the DB columns.

I realize not having to iterate through the results over again is a plus.  But given node's event loop and possibly keeping PG client's connection open longer might be not desired as well.

**Comment by riston** [comment]
Good I had similar question, also does the PostgreSQL "driver" protocol transfers the full result after the query has been executed or allows streaming approach ?

Also the JSON format in PostgreSQL becomes more popular the approach of returning single huge JSON object is not good for the event-loop (json data size about >100kb).

Single row return from PostgreSQL:
```
{
   "user": {... },
   "lists": { },
   "tasks": { }
}
```
Better would be if the dataset could be broken into flat structure and returned as multiple rows.
```
// First row
{
   "user": {}
}
// Second row
{
   "lists": {}
}
// Third row
{
    "tasks": {}
}
```



Event based approach, get the rows with the event and when 'end' is thrown we should have full dataset.
```js

var conString = "postgres://localhost/test";

var client = new pg.Client(conString);
var startTime;

var connectCb = function (err)
{
    if (err)
    {
        return console.error('could not connect to postgres', err);
    }

    startTime = Date.now();
    var query = client.query("SELECT data FROM json.read_single");

    query.on("row", function (row, result)
    {
        result.addRow(row);
    });

    query.on("end", function (result)
    {
        console.log("Fetch end ", result.rows);
        console.log("End time", Date.now() - startTime);
        client.end();
    });
};

client.connect(connectCb);
```


Get all the results from callback.
```js

var pg = require("pg");

var conString = "postgres://localhost/test";

var client = new pg.Client(conString);
var startTime;

var connectCb = function (err)
{
    if (err)
    {
        return console.error('could not connect to postgres', err);
    }

    startTime = Date.now();
    client.query("SELECT data FROM json.read_data", queryCb);
};

var queryCb = function (err, result)
{
    if (err)
    {
      return console.error('error running query', err);
    }

    console.log(result.rows);
    console.log("End time", Date.now() - startTime);
    client.end();
};

client.connect(connectCb);

```

**Comment by brianc** [comment]
Hey - good questions!

@epikhighs: it almost assuredly doesn't matter.  Unless you're receiving hundreds of thousands of rows in a single query looping through the array one more time is going to take ~1-2 milliseconds. Premature optimization most definitely.  As with any perf hunt the best approach is to profile first and only then change the hot paths & things that are causing slowdowns.  I've found its generally not where you'd expect them to be.  Also if you really wanna get __huge__ result sets back you probably wanna use https://github.com/brianc/node-pg-query-stream - otherwise you're gonna end up blowing up your memory space.  99.999% of the time I just use https://github.com/brianc/node-pg-query to run queries in production projects - build your app.  If performance becomes an issue only then try to benchmark & figure out why.  Or write the whole thing in C/C++. :trollface: 

@riston the protocol itself allows a streaming approach but its only supported with the pure-javascript driver.  To actually _stream_ results you need to use https://github.com/brianc/node-pg-query-stream.  libpq internally buffers all rows into memory before handing them off to the consumer so there's no way to stream rows with the native bindings at this time.
