### ISSUE TITLE
Increased number of connections with node 4

### ISSUE THREAD

**Issue by Chris911** [brianc/node-postgres#871]
We are in the process of updating from node 0.10 to node 4.1.2 and we're seeing weird patterns in the number of connections to postgres. The number of connections doubles when we use 4.1.2 in production with pg 4.4.1. Any idea what could be happening here?

Connections: 
<img width="552" alt="screen shot 2015-10-06 at 2 05 06 pm" src="https://cloud.githubusercontent.com/assets/1198196/10338940/c0dc49da-6cd6-11e5-9ee3-7446c229b3ca.png">

**Comment by cdnbacon** [comment]
Could this be related to the pooling issue on node 4.1?

https://travis-ci.org/brianc/node-postgres/builds/83819736

![image](https://cloud.githubusercontent.com/assets/1574577/10343246/ed74c6fc-6cea-11e5-9478-42f0d2fd7391.png)

**Comment by brianc** [comment]
@cdnbacon I'm not sure what pooling issue you're referring to.  The travis test failures are because there's some additional config you have to pass to travis to get it to compile under all the various different versions of node I haven't been able to find the time to figure out travis - the pooling itself hasn't changed in a _long_ time.  If you look at the test results you linked all the pure javascript integration tests pass before that suite fails which is a decent indication there's nothing wrong w/ the pooling itself.

@Chris911 - I don't know of any reason in node-postgres that would be happening.  If you look at the code history / changelog the pooling code hasn't changed in a long while.  Also I'm assuming you're using the same version of `pg` on both versions of node so that's probably ruled out anyways. :stuck_out_tongue_closed_eyes:  If you dive in and figure out anything I'd love to hear back about it of course!  It might be an environment issue on your end - spinning up more workers or something?  Otherwise not sure what to tell you without some time to dive into this issue - and I wont have any free time on that for probably quite a while.

**Comment by brianc** [comment]
Good news! I just fixed travis. :dancer:

**Comment by Chris911** [comment]
Thanks @brianc. Yes we are using the same version of `pg` in both cases and honestly I do not think the problem is coming from `pg` but I thought I'd ask just in case anyone had seen something similar. Will let you know if we figure it out.

**Comment by abenhamdine** [comment]
Perhaps this is related to the lower  memory consumption on node 4.X, which is approximatively 1/4 of Node 0.1x consumption?

**Comment by cdnbacon** [comment]
> I'm not sure what pooling issue you're referring to.

Thanks @brianc, the commit description in the [travis screenshot I shared](https://github.com/brianc/node-postgres/issues/871#issuecomment-146243692) was what I was referring to. Based on your comment though, it doesn't seem like much of a lead for explaining the root cause of the connection increase.
