### ISSUE TITLE
Prepared Statement creation only (without execution) throws an error

### ISSUE THREAD

**Issue by diffen** [brianc/node-postgres#903]
When using prepared statements for insert, I'd like to create the prepared statement once (e.g. outside router.get in Express), and then use that statement when processing HTTP requests.

But when only text and name are supplied e.g. 
```
client.query( {
    text :  "INSERT INTO my_table(field1,field2) VALUES ($1, $2)", 
    name : "insert-my-data"
});
```

then it throws an error:
> error: bind message supplies 0 parameters, but prepared statement "insert-my-data" requires 2

The [documentation](https://github.com/brianc/node-postgres/wiki/Client#method-query-prepared) says:
> If text and name are provided within the config, the query will result in the creation of a prepared statement.

I understood that to mean providing **value** is optional, but looks like it's not.

**Comment by brianc** [comment]
Yeah right now its not optional to provide params.  If you want, you can supply the name of the query via the `name` property _every time_ you run the query.  pg keeps a client-side list of what statement is prepared on each client & only prepares it the first time.

This is actually the better approach because if you prepare a statement on one client and then try to execute a prepared statement on another client the server wont know what you're talking about. You have to prepare the statement _once per client_. so...go ahead and supply the `name` option to every query, pg will "do the right thing" for you. :tm:

**Comment by diffen** [comment]
Thanks, Brian! So let me see if I understand this correctly:

**value** is not optional for prepared statements. So we cannot simply create a prepared statement without actually executing it. But this isn't that big of a problem because if I pass the **name** and **text** with every query, pg will first check to see if the statement with that name is already prepared. If it is, then **text** will be ignored (rather than the prepared statement being updated with the "new" text) and the prepared statement will be used.

And since prepared statements are cached *per client*, and we usually use a pool of clients, it's good to use both **name** and **text** in every prepared statement. That way if the statement is cached, it won't have to be prepared again.

Is that correct?

**Comment by brianc** [comment]
You got it!  Pass `name` `values` and `text` to every query you want to be
prepared.

**Comment by brianc** [comment]
Lemme know if anything else is unclear!

**Comment by vitaly-t** [comment]
@brianc Now I'm not sure if my implementation is good at this point...

Here's what I did...

I created my own PreparedStatement object that can create a simple `{name, text, values}`, but it only sets `text` if it has changed since the last we called, or if `client.secretKey` value has changed since the last call.

My tests show that it works. But following previous posts, I'm not sure if such logic will always work, or whether it is a good solution at all?

Please help me understand this!

**Comment by langpavel** [comment]
@vitaly-t This is reason why I start writing my own library. You have your own parameters escaping logic, that actually forbids prepared statements as I understand it because you bypassing argument passing.

**Comment by vitaly-t** [comment]
@langpavel you understand it wrong, that is not the case. Prepared Statements have always worked through the server in pg-promise, as they should. Anyhow, if you have questions, this is not the place.

I asked my question there for a reason.
