### ISSUE TITLE
Request: mention pg-rxjs in Readme

### ISSUE THREAD

**Issue by jadbox** [brianc/node-postgres#915]
I've created a library forked from pg-then that's for specific Rx: 
[pg-rxjs](https://github.com/jadbox/pg-rxjs)

Almost full code coverage is included.

**Comment by sibedge** [comment]
@jadbox you could reduce all that code to about 10% of it, using [pg-promise](https://github.com/vitaly-t/pg-promise), because it already has [automatic transactions](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#transactions) in it, plus [automatic streaming through pg-query-stream](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#streaming).

**Comment by jadbox** [comment]
@sibedge I too use QueryStream for the Stream operator. I do like pg-promise though, but it's not as thin as a Iayer I was wanting for pg-rxjs. Also, wrapping Rx over promises creates unnecessary performance issues by having the two handshake.

**Comment by rpedela** [comment]
Fork, modify readme, and make a pull request.

**Comment by jadbox** [comment]
^ done and done
