### ISSUE TITLE
EXECUTE format with params does not work

### ISSUE THREAD

**Issue by ottoville** [brianc/node-postgres#922]
Following statement does not work:
conn.query("EXECUTE format('INSERT INTO %I (col) VALUES ($1)', my_table)",['myvalue'],function(e,results) {
 })

Expected result:
Insert row into "my_table" with col value "myvalue"

Actual result:
[error: bind message supplies 1 parameters, but prepared statement "" requires 0]

**Comment by jonahbron** [comment]
:+1:

**Comment by brianc** [comment]
I'm not sure that's supported w/ the postgres protocol.  You'll likely need to read up on postgres documentation to see if that's even possible. My hunch says its not since I don't do anything to your query, just pass it into postgres - generally these kind of things are related to unsupported query and/or parameterization syntax
