### ISSUE TITLE
LISTEN notifications stop after a while

### ISSUE THREAD

**Issue by super-cache-money** [brianc/node-postgres#967]
I'm using `LISTEN` to be notified of changes. It used to work perfectly when I was listening to a DB on `localhost`. However, now that I've moved the DB over to another VM, I'm encountering some problems where my client loses "sync" with the DB and stops receiving notifications after some time (in order of minutes/hours). 

I'm not using the connection pool, here's how I connect and listen to updates: 

```
var client = new pg.Client(pgConString);
client.connect(function(err, client) {
    if(err) {
      throw err;
    }
    client.on('notification', function(msg) {
        console.log(msg.payload);
    });
    client.on('error', function(error) {
      console.error('This never even runs:', error);
    });
    var query = client.query("LISTEN watchers");
});
```

Is it possible keep this listener working indefinitely? Am I doing something silly? What is supposed to happen after a momentary network failure? Do I have to resign to polling the DB and diffing changes?

**Comment by vitaly-t** [comment]
Did you check what other events, if any, does your client object receive? See if it gets suddenly disconnected for some reasons.

**Comment by super-cache-money** [comment]
I've just listened for all of `end`, `done`, and `error`. None are fired when I lose connection.

**Comment by vitaly-t** [comment]
One of the main reasons why this library moved mostly into the use of the connection pool is because it is very awkward dealing with dropped connections, while the pool can maintain connections automatically.

But with the event listening it is impossible to use the pool, because each connection in the pool has an expiration on it.

If you cannot detect a dropped connection through the client interface, you can try and detect it otherwise, and once detected, re-establish the watcher.

If you suspect a networking failure, you can listen for that, somehow.

Like I said, static connections are awkward.

**Comment by super-cache-money** [comment]
Thank you @vitaly-t . If fixing this falls outside of the scope of this library, I'm happy to close this issue.

**Comment by vitaly-t** [comment]
@super-cache-money I'm 50% certain that it does, so do as you please ;)

**Comment by super-cache-money** [comment]
FWIW, I am considering using this library to listen for events on the same server as the DB, so that the connection never fails. I'll then pass the notifications to another messaging client (maybe [rabbitmq](http://www.rabbitmq.com)? ) which can broadcast robustly to the remote servers. LMK if that sounds dumb.

**Comment by vitaly-t** [comment]
Sorry, I'm not an expert at either to pass a judgement. Try, see if it works ;)

**Comment by ReinsBrain** [comment]
Still open - I'd very much like to use NOTIFY/LISTEN and hoping work on pg may have since resolved this issue since it was posted. Can anyone comment? If the problem persists, I was thinking that I could simply re-establish the connection ( and LISTEN query ) on a routine basis ( say every minute )... thoughts?

**Comment by vitaly-t** [comment]
I started in [pg-listener](https://github.com/vitaly-t/pg-listener), but never finsihed it, maybe later.

As of today I know of only one usable implementation: [node-pg-pubsub](https://github.com/voxpelli/node-pg-pubsub).

**Comment by pankleks** [comment]
Hi - I'm facing same issue.
I understand that connection on which I'm issuing pg.on('notification') has been dropped, and due to connection pooling - it was invisible.
So it there a way to get notification on connection drop/error so I can issue new pg.on(...) on new connection?

**Comment by vitaly-t** [comment]
@pankleks as of today, [node-pg-pubsub](https://github.com/voxpelli/node-pg-pubsub) is your best shot :wink:

**Comment by super-cache-money** [comment]
@vitaly-t @pankleks yeah, tried that with no success too :(

**Comment by super-cache-money** [comment]
ended up routing the notifications through rabbitmq. That was a hastle.

**Comment by vitaly-t** [comment]
@super-cache-money that didn't work? Did you log a bug against that library?

I want to know what happened, because I awhile ago I started on an alternative ([pg-listener](https://github.com/vitaly-t/pg-listener)), but never finished because it looked like there was no need.

**Comment by super-cache-money** [comment]
I didn't log anything....
I seem to remember that it had the same problem of seizing up. When I checked after a few days after running it, notifications stopped arriving.

When I have time I'll see if I can do a more detailed post mortem.

**Comment by pankleks** [comment]
Thanks guys, but I still try to understand the issue.

How I can get info that connection has been dropped.
I subscribed on Client "error" and "end" but none of them were fired, and notification stopped working anyway.

**Comment by pankleks** [comment]
Ok, I think I solved my problem - maybe it will help others.
In fact I did obvious mistake - connection I used for subscribing for notification was taken from pool.
When I created "exclusive" connection (by new Client(...)) it works fine.

Here is snapshot of piece of code that could be reused:
```typescript
    listen(fn: (message: { channel: string, payload: string }, client: Pg.Client) => void, ...channels: string[]) {
        let
            client = new Pg.Client(this._config);

        client.connect((err) => {
            if (err) {
                console.error(`Can't connect listener.`);

                setTimeout(() => {
                    this.listen(fn, ...channels);
                }, 1000 * LISTEN_RECONNECT_S);
            }

            client.on("notification", (message) => {
                fn(message, client);
            });

            client.on("error", (err) => {
                console.error(`Lost connection for listener.`);
                this.listen(fn, ...channels);
            });

            for (let e of channels)
                client.query(`LISTEN ${e}`);
        });
    }
```
If connection is dropped, it will try to reconnect immediately, if this one fails too - it will do timeout to attempt again after some time.

Hope it helps:)

**Comment by doesdev** [comment]
Just wanted to chime in with a solution in module form. I've been working with a milder iteration of this in prod for some time, but decided it might make for a useful module. There's nothing much to it. The only couple of tricks are that it forces `keepalive` on the underlying socket (mentioned in another issue I believe) and brute force retries on failure. 

More or less it will ping a notify every X seconds and keeps track of the last successful message, not bubbling the test message to the client. If it fails it will reopen the listener with Postgres and keep chugging. In the interim period (between a disconnect and reconnect) messages will be lost, so it isn't guaranteed that all messages come through in the event of a failure, It's useful if you don't need guaranteed messages 100% of the time, otherwise other solutions should be used.

Anyway, hertis: [pg-ears](https://github.com/doesdev/pg-ears)

**Comment by brianc** [comment]
nice @doesdev - I've got some stuff on the 7.0 milestone to handle network partitions better & do research into why sometimes connections drop but don't report.  I have a hunch it has to do w/ not setting heartbeats on the tcp connection to the backend, but I haven't dug in yet.  I guess the somehwat good news is it's on my radar. :smile:
