### ISSUE TITLE
One session per client?

### ISSUE THREAD

**Issue by calebmer** [brianc/node-postgres#987]
Quick question that I can't be 100% sure of because of some of the auto-pooling `pg` does—Does every instance of `Client` have its own PostgreSQL session? So every instance returned by `require('pg').connect` or instantiated with `require('pg').Client`.

**Comment by vitaly-t** [comment]
Method `connect` pulls the connection from the pool, based on the connection parameters.

The situations when a new connection is created:

* There haven't been any connection created yet
* There is no open connection i the pool that matches the specified connection parameters
* The connection was there in the pool, but it expired due to non-use

**Comment by calebmer** [comment]
Thanks!
